### ISSUE TITLE
BFO-2020 branch: temporalized relation considerations

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#106]
1) If there is a sub- or super-properties P of one the temporalized relations such as continuant-part-of-at-some-time, then in some cases P will also need to be temporalized. Each sub- or super-property needs to be evaluated to determine if it should be temporalized. 

2) Outside the above, any property involving a continuant needs to reviewed in order judge whether property is implicitly time-dependent. If so the relation will need  at-all-times and/or an at-some-time version.

Examples:
* The realized-as relation relates a continuant to an occurrent, but the relation is **not**  time indexed.
* The participates-in relation also relates a continuant to an occurrent, but in this case it **is** time indexed. 
* The CCO affiliated-with implicitly depends on time, as affiliations can change. 

In some cases where a temporalized relation P is needed, the intended meaning of the existing binary relation clearly matches either the some-time or all-times version. In that case P's label can be changed (or not) to P-at-some-time and the original IRI is retained. 

BFO's has-participant relation is such a case. It was understood that the participation meant has-participant-at-some-time. That's because it couldn't be an at-all-times relationship if you want to represent processes where something is created. The created thing also participates, but it does not participate for the whole time the process exists.  Because of this BFO-2020 kept the has-participant IRI, but changed it's label to has-participant-at-some-time.

With affiliated-with the sense also seems to be at-some-time. In that case, again, the original affiliated-with IRI is kept, since the meaning of the term hasn't changed, and the label can be changed to affiliated-with-at-some-time if desired.

**Comment by johnbeve** [comment]
@alanruttenberg @APCox @mark-jensen I believe we can close this issue as OBE.
