### ISSUE TITLE
Use slash rather than hash in IRIs

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#108]
When I submitted #105 I forgot to include mention of the choice of separator, so I'm opening a new issue to address that. The main reason to use slash versus hash IRIs is that the former allows single term access and display. Since the URI fragment is not included in the IRI that is accessed when following a link, requesting a single hash IRI results in retrieval of the whole ontology.

**Comment by mark-jensen** [comment]
@alanruttenberg All CCO IRIs should be in the form:

`http://www.ontologyrepository.com/CommonCoreOntologies/TERM_ID`

Where are you seeing hashes? Are you looking at the default or base prefixed namespaces in the .ttl files? These sometimes get autogenerated during updates, often from the ontology IRI. All CCO files explicitly declare the "cco:" prefix for the correct namespace.

**Comment by alanruttenberg** [comment]
Closing this issue now that it is clear that CCO uses slashes.
