### ISSUE TITLE
Should IRIs be http or https?

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#109]
As the world moves to uniform use of https, we should consider whether to have our identifiers https as well. OBO uses http, and I now worry a bit about whether they will be harder to use in the future.

A non-solution is to allow both. Since every character in an IRI is significant, this amounts to having two ids for every term.

**Comment by neilotte** [comment]
@alanruttenberg Agreed. 

Posting a small discussion with reps from FIBO found in googling around on this topic: https://lists.w3.org/Archives/Public/semantic-web/2017Jul/0044.html May be of interest.

**Comment by alanruttenberg** [comment]
The document referenced in the discussion by Harry Halpin is
[Semantic Insecurity: Security and the Semantic Web](https://hal.inria.fr/hal-01673291/document)

Haven't read it yet, but will.

The main concern I have at this time is about systems not being actively maintained and at some point having cert timeouts, rendering them unusable.

**Comment by johnbeve** [comment]
@alanruttenberg @APCox @mark-jensen Was a decision reached on whether to use http or https?

**Comment by neilotte** [comment]
This issue will be addressed in 2.0.

**Comment by alanruttenberg** [comment]
If it is yet to be addressed, then it isn't completed. Consider adding a label.

**Comment by neilotte** [comment]
@alanruttenberg I've added an issue to track the larger issues under 2.0. This issue references the multiple lines of discussion on this matter, including this one. See: https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/421
