### ISSUE TITLE
examples of usage for prescribes don't mention prescribes

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#111]
Here's an rough attempt to modify the definitions to use the term prescribes
 
* a blueprint prescribes some artifact or facility by being a model for it.
* a professional code of conduct prescribes some realizations of a profession (role) by giving  rules for how the bearer should act in those realizations.
* An operations plan prescribes an operation by enumerating the tasks that need to be performed in order to achieve the objectives of the operation.

**Comment by neilotte** [comment]
@mark-jensen I've labeled this for 1.6 and assigned to you.
