### ISSUE TITLE
Cite Common Core Ontologies

### ISSUE THREAD

**Issue by lizumberfield** [CommonCoreOntology/CommonCoreOntologies#119]
I am interested in citing the Common Core Ontologies in a manuscript. What publication or artifact would you ask that I point to?

Thank you,
Liz

Elizabeth Umberfield, PhD, RN
Postdoctoral Research Fellow
Public & Population Health Informatics
Regenstrief Institute and Indiana University Fairbanks School of Public Health

**Comment by eliasweatherfield** [comment]
You could cite it the way proposed [here](http://www.obofoundry.org/docs/Citation.html), perhaps with CUBRC, Inc. as institutional/group author.

**Comment by APCox** [comment]
@lizumberfield If you want to cite the ontologies themselves, use:

> CUBRC. (2017-2021). Common Core Ontologies GitHub repository. Retrieved from https://github.com/CommonCoreOntology/CommonCoreOntologies

NB: Development of he CCO began in 2010, but was made public on GitHub in 2017.
For the CCO white papers available in the Documentation folder [here](https://github.com/CommonCoreOntology/CommonCoreOntologies/tree/master/documentation), use:

> CUBRC. (2020). An Overview of the Common Core Ontologies 1.3. Common Core Ontology White Paper.  Retrieved from https://github.com/CommonCoreOntology/CommonCoreOntologies/blob/master/documentation/An%20Overview%20of%20the%20Common%20Core%20Ontologies%201.3.docx
> 
> CUBRC. (2017). Modeling Information with the Common Core Ontologies 1.0. Common Core Ontology White Paper.  Retrieved from https://github.com/CommonCoreOntology/CommonCoreOntologies/blob/master/documentation/Modeling%20Information%20with%20the%20Common%20Core%20Ontologies%201.0.docx
> 
> Rudnicki, R., Smith, B., Malyuta, T., & Mandrick, W. (2016). Best Practices of Ontology Development. Common Core Ontology White Paper.  Retrieved from https://github.com/CommonCoreOntology/CommonCoreOntologies/blob/master/documentation/Best%20Practices%20of%20Ontology%20Development.docx

If you want to cite a single document about the CCO, I recommend the latest version of "An Overview of the Common Core Ontologies", which is currently version 1.3.

There are additional publications about using the CCO to solve specific challenges or represent specific domains, which are not listed in the documentation, but may also be relevant depending on your use case.

**Comment by lizumberfield** [comment]
Thank you.
