### ISSUE TITLE
Are all artifacts objects?

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#120]
For instance, is a loaded gun an artifact? That's an object aggregate. I'm trying to find another compelling example. Maybe something like an instrument that has, as part, a magnetically levitated piece. Are there gyroscopes like that?

This was prompted by something mentioned during a DICO meeting.

Tagging @harefb

**Comment by alanruttenberg** [comment]
Here's one: [Magnetically Levitated Solar Motor](https://www.gyroscope.com/d.asp?product=SOLARMOTOR4)

**Comment by rorudn** [comment]
If there isn't a problem with artifacts being assembled from parts and still being objects ("...the division of certain portions of reality into engineered units (manufactured artifacts) is the basis of modern industrial technology, which rests on the distributed mass production of engineered parts through division of labor and on their assembly into larger, compound units such as cars and laptops."), then why is it that a gun loaded with bullets is no longer an object but an object aggregate? This seems the same as a transmission being filled with fluid. Neither the gun nor the transmission will work as intended without these parts. In the motor example you give the parts are connected through magnetic force just as the parts of a sofa are connected through gravitational force. If its not a problem for the sofa then why for the motor?

**Comment by alanruttenberg** [comment]
The argument for gun and bullets may be weaker but my gut still says aggregate. Trying to figure out where the intuition is coming from. Couple of things are  that the bullets are not fastened to the gun, and that there are exchangeable magazines that extend the gun and are not essential. We don't consider the oii in an oil talk to be part of the oil tank, and the bullets seem analogous. 

The motor seems clear though. If the bottom moves but if the top moves the bottom doesn't(maybe a little). That's one of the causal unity criteria that Barry lists. I mean, if two substantial objects that are not touching doesn't form an aggregate, how can you differentiate from the other cases where the physical separation indicates aggregate? Re gravity: I am not part of the earth even though I am held to it by gravity, nor are the planets part of the sun. 

Object aggregate and object are not disjoint and so it is possible to be both, but the usual case is of a granularity difference. The molecules in a rubber ball make it an aggregate but macroscopically it is an object.

You don't really gain any leverage by calling it a material entity vs object, so from a practical point of view you don't lose anything. But keeping it where it is brings up difficult questions that would need to be addressed. Sometimes it makes sense to commit to less,

**Comment by alanruttenberg** [comment]
Another example: [Distributed Array Radio Telescope](http://mercury.pr.erau.edu/~prcphysics/observatory/DART.htm)

More extreme: A hole drilled into a tree. That's an immaterial entity. Or lover's initials carved into a tree. In that case the artifact is, arguably, a quality.

**Comment by alanruttenberg** [comment]
You could rule out the hole and carvings by defining 'material artifact', which can then be restricted to material entities. I don't see a similar move that will help with material entity vs object.

Another immaterial - a basic carved out of a rock, to collect water. That's "designed by some Agent to realize a certain Function". I think that part of the definition is more important than the "an object that" part.

**Comment by bdonohue29** [comment]
To press on this question a bit further, though from a different direction: many (most? potentially all?) Information Content Entities seem to be artifactual.

Moreover, capturing the Information Bearing Entity as an Artifact would not appear to be sufficient. Yes, the blue piece of paper that bears the Artifact Design is an Artifact -- but isn't the Artifact Design itself artifactual?

To clarify, I'm not trying to quibble over terminology. In CCO, the class "Artifact" is defined in such a way that it is, of necessity, an object, and thus a material entity, and thus an independent continuant. Accordingly, there's no question: ICEs obviously could not be "Artifacts" in the present CCO sense of the term.

Rather, what I'm pushing on more here is the idea that the content itself can be the product of design, and wondering where that fits into CCO's ontological approach to artifacts. In this regard, intellectual property generally may be a good example to ponder.

**Comment by alanruttenberg** [comment]
My suggestion of having a term 'material artifact' was a way to make them parallel. "artifact' can then be, if desired, a defined class of anything that is information or the material artifact. That's only a label and only the definition really matters, but the idea would be to define the new term as a material entity that... 

That still leaves out immaterial artifacts, like national borders, etc. A decision would need to be made whether there should be a separate class for these, or whether a single class that captures both these and material artifact is more desirable.

If you are wondering why I didn't suggest 'material object' it's that the distinction between material entity and anything else is easy to get. The distinction between object and other material entities, not always so easy. Also, I'm guessing that 'material object' isn't what's really wanted - I think for the purposes of CCO the DART and the Maglev motor would be expected to be classified below the artifact term.

**Comment by cameronmore** [comment]
@alanruttenberg Since we have the term 'Material Artifact', and it's a subclass of Material Entity and not object, has this issue been addressed?

**Comment by alanruttenberg** [comment]
yes
