### ISSUE TITLE
Are requires, prohibits, permits supposed to be reducible? 

### ISSUE THREAD

**Issue by nklsbckmnn** [CommonCoreOntology/CommonCoreOntologies#122]
x requires y at t iff: x is an instance of Action Regulation at time t, and y is an instance of Act at time t, and x prescribes that some agent must be agent in y.

x prohibits y at t iff: x is an instance of Action Regulation at time t, and y is an instance of Act at time t, and x prescribes that some agent must not be agent in y.

x permits y at t iff: x is an instance of Action Regulation at time t, and y is an instance of Act at time t, and x prescribes that some agent may be agent in y.

I was wondering if these relations are supposed to be reducible, meaning that it would be justified to infer e. g. for requires

x requires y -> x prescribes Agent z, Agent z participates in y

I guess x prescribes Agent z and Agent z participates in y are not sufficient for x requires y because they don't express the "must be", but necessary.

This would lead to x prescribing two Entities. (I wondered about the possibility of multiple entities in a modal subgraph being prescribed by a Directive ICE in #64.)

Any ideas? Thanks.

**Comment by bdonohue29** [comment]
Opinion:
- Correct, "x requires y" doesn't entail "x prescribes Agent z and z participates in y"
- Agreed, if an Action Regulation specifies a particular Agent, this would get specified in the Modal subgraph: "x prescribes y, and y mro:has_agent Agent z," etc.

**Comment by eliasweatherfield** [comment]
Thanks for your insight.

> Agreed, if an Action Regulation specifies a particular Agent, this would get specified in the Modal subgraph: "x prescribes y, and y mro:has_agent Agent z," etc.

That's always an option, I guess.

But I was thinking about sth. like this: (two entry points into the modal subgraph)

x mro:prescribes Process y
x mro:prescribes Agent z
y mro:has_agent z

I'm not sure what the semantic difference between this and 

x mro:prescribes Process y
y mro:has_agent Agent z

amounts to.

**Comment by neilotte** [comment]
@nklsbckmnn We have begun to move discussions items to the discussion forum. Please consider adding a thread there regarding this question if it is still open.
