### ISSUE TITLE
Rename "artifact" "material artifact" 

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#123]
It is reasonable to consider a site or a boundary an artifact. Without making a decision about that, it seems harmless to do this renaming which will be appropriate however the artifact discussion is resolved.

**Comment by swartik** [comment]
In the OED, definition 3 of artifact is:

> A non-material human construct.

so the word definitely includes the non-material realm. The OED cites sentences that consider politics, poetry, and mathematics as artifacts.

Should the same argument be made about object? BFO is using "object" in the sense of a material thing, but the word has other meanings:

> A goal, purpose, or aim; the end to which effort is directed; the thing sought, aimed at, or striven for.

Given the place of both artifact and object in the class hierarchy, it's clear they denote material entities. In other words, neither of the definitions I cited applies. The challenge is to make that clear.

Especially if (when?) CCO renames classes using opaque identifiers, I am less concerned with the label than with the definition. I would strive for more precision in the definitions, and perhaps elucidation annotations.

**Comment by cameronmore** [comment]
Since artifact has been renamed, this issue seems to be resolved.
