### ISSUE TITLE
delmit relation 1:1?

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#125]
It's declared functional and inverse functional so 1:1.

Delimits:
>An instance of Geopolitical Entity gpe1 delimits some Organization o1 iff gpe1 is the area within which o1 can legally operate.

Geopolitical entity:
>A Geospatial Region that delimits the authority of a formally constituted Government to exercise its control within the bounded area.

1. The property's range is organization, though the definition of Geopolitical entity suggests it should be the more narrow govt.
2. If government, aren't there places which have shared control? In which case it wouldn't be inverse functional
3. If organization, couldn't several organizations be delimited by the same Geopolitical entity, in which case it wouldn't be functional?

**Comment by neilotte** [comment]
This issue appears to have been addressed in a prior release as the property is not functional.
