### ISSUE TITLE
Revise the object property 'has member of located in'

### ISSUE THREAD

**Issue by APCox** [CommonCoreOntology/CommonCoreOntologies#127]
There are a number of potential problems with this object property:

- Both the label and definition are awkward and the two seem to be at odds with one another.
-- The label would read better as 'has member located in'.
-- The label seems to imply that a single member (or perhaps at least 1 member) is located there, but the definition explicitly states that it only holds when all members are located in the same material entity. If the definition is the intended meaning, then the triple ObjectAggregate A located_in L should be sufficient. So, either the definition should be changed or the term should be removed.

- Is this relation intended to be a shortcut, such as ObjectAggregate A has_member M located_in L? If so, this axiom should be added as a super property chain.
- Why is the range 'material entity' when the range of 'located in' is 'independent continuant'? This restriction limits the usability of the relation to exclude sites and spatial regions.
- This is not (nor should it be) a symmetric relation, but I was unable to identify an inverse for it.

**Comment by neilotte** [comment]
@APCox  Can you open a PR to address these updates?
