### ISSUE TITLE
Mean Point Estimate Information Content Entity parent missing

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#128]
The term *Mean Point Estimate Information Content Entity* is defined as
>A Ratio Measurement Information Content Entity that is a measurement of a set of values and is equal to the sum of all the values in the set divided by the total number of values in the set.

There is a class *Ratio Measurement Information Content Entity* however this class is neither the asserted parent or an inferred parent.

*Ratio Measurement Information Content Entity* is equivalent to ('is a ratio measurement of' some entity) so that axiom could be added to *Mean Point Estimate Information Content Entity* so that the reasoner classifies it properly. Or, if it's a cut and paste error then the superclass could be corrected.

**Comment by rorudn** [comment]
I think you meant "A Mean Point Estimate Information Content Entity is defined as"

The current definition does incorrectly mention Ratio Measurement Information Content Entity as the parent class. This will be changed to mention Point Estimate Information Content Entity instead.

**Comment by swartik** [comment]
This is an opportunity to address definitions of the siblings of Mean Point Estimate Information Content Entity, which are also problematic:

- Mode Point Estimate Information Content Entity says its parent is Nominal Measurement Information Content Entity.
- The definition of Median Point Estimate Information Content Entity doesn't follow the "A _parent_ that ..." paradigm.

**Comment by mark-jensen** [comment]
These are fixed on a [branch](https://github.com/CommonCoreOntology/CommonCoreOntologies/commit/b02dd5350bfedf9cfb84c03ee975fb694ae0b9c9) and shall be part of the next release.

Median = A Point Estimate Information Content Entity that is a measurement of a set of values and is equal to either the middle value or the average of the two values which separate the set into two equally populated upper and lower sets.

Mode = A Point Estimate Information Content Entity that is a measurement of a set of values and is equal to the  values(s) that occur most often in the set.

Mean = A Point Estimate Information Content Entity that is a measurement of a set of values and is equal to the sum of all the values in the set divided by the total number of values in the set.
