### ISSUE TITLE
Authority Role and Organization Member Role

### ISSUE THREAD

**Issue by PhiBabs935** [CommonCoreOntology/CommonCoreOntologies#129]
Hi,

So I am working on a Military Ranks Ontology which is intended as an extension of CCO and related ontologies. Associated with the rank classes I built are subclasses of Authority Role that persons have in virtue of their ranks (e.g. 'General role', 'Lieutenant role').

Now a general or lieutenant can also be classified as members of an organization (military), and so they have responsibilities in virtue of being part of that organization. Which suggests an Organization Member Role. But of course I don't want to assert the 'General role' as a child of both CCO classes. Would I need separate role classes for the responsibilities of generals, etc?

**Comment by cameronmore** [comment]
Jonathan Vajda @jonathanvajda has done a lot of work in this area extending from CCO into the domain of deontic roles, authority, and related concepts (as opposed to the OBO counterpart Informed Consent Ontology). The ontology can be accessed [here](https://github.com/jonathanvajda/cco-d-acts), and I think the design pattern he has in mind is that some roles may have other role parts--being a General involves some other associated roles of responsibility and also authority roles, each having the same organizational context.

**Comment by PhiBabs935** [comment]
Yeah, I've been making use of Jon's stuff recently in connection with CBP projects. Thanks!
