### ISSUE TITLE
affiliate vs. member

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#13]
I'm looking for the relation between a member of a group or organization and the group or organization to which they belong. I don't see 'member of' among the relations, and 'has affiliate' is undefined. 

Thoughts?

**Comment by bdonohue29** [comment]
member_of was recently added to CCO (long time coming) as a relationship between aggregates and their members, but has not yet made it into the github release.

In the meantime, you might say:
* person1 has_role role1
* role1 has_organizational_context organization1

**Comment by neilotte** [comment]
Thanks.

**Comment by APCox** [comment]
Changes in version 1.1:
added definition for 'is affiliated with'
added 'member of' and 'has member'
