### ISSUE TITLE
NATO rank codes & pay grade codes ICE placement

### ISSUE THREAD

**Issue by PhiBabs935** [CommonCoreOntology/CommonCoreOntologies#130]
I am creating classes for NATO rank codes and US armed forces pay grade codes for the Military Rank Ontology. I am not sure where these would go within the CCO ICE hierarchy. Any guidance would be appreciated.

**Comment by cameronmore** [comment]
Personally it seems beyond scope, belonging in a NATO Organization domain ontology.

@mark-jensen

**Comment by PhiBabs935** [comment]
@cameronmore
Hi Cameron. Haven't worked on this in a while. But my question may not have been clear. I think back then was trying to fish out confirmation as to whether or not it would be a subclass of 'Code Identifier' or not.

**Comment by cameronmore** [comment]
I think I misread your comment initially, and it seems like it. The rank code seems to identify a role that one may bear.
