### ISSUE TITLE
Add definition source for Allen and RCC8 inspired terms.

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#131]
I was looking for these and realized I had to find them by name. It would be helpful to cite sources for the two so it would be easier to find as well as for users to be able to find further information in the literature.

**Comment by mark-jensen** [comment]
@alanruttenberg This is a good idea. I'll work on it.

**Comment by neilotte** [comment]
@mark-jensen  Was this addressed?
