### ISSUE TITLE
What terms belong in a mid-level ontology?

### ISSUE THREAD

**Issue by jimschoening** [CommonCoreOntology/CommonCoreOntologies#135]
At the 5 Aug MLO Mtg, Barry Smith proposed we adopt rules of what terms belong in a Mid-Level Ontology (MLO) and which do not. The Project Proposal states, “A mid-level ontology is a set of terms, definitions, and relations commonly used across multiple domains, which will enable conforming extensions for specific domains or applications.

The following are strawman rules for how to determine if a term belongs in a Mid-level ontology (which will require governance to implement). 
Rule 1) If a term is used (and needed) in two or more significant extensions, it should be moved up to the MLO.  Likewise, if a term in a MLO is only needed in one significant extension, it should be moved down to that extension. 
Rule 2) If Rule 1 causes an MLO is too big (or projected to get too big), terms used mostly in one domain may be moved down to that extension, and other other extensions will then need to refer to that term in the other extension.

**Comment by johnbeve** [comment]
@mark-jensen @cameronmore @APCox Am I right in thinking this is OBE given the direction we've been taking in the IEEE meetings regarding the MLO criteria? If so, we can close this issue.

**Comment by mark-jensen** [comment]
Agreed.
