### ISSUE TITLE
Temporal region identifiers and BFO-2020

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#141]
Temporal instant identifier is currently defined as designating some 'zero dimensional temporal region', and analogously for interval. BFO-2020 has classes for instants as opposed to zero-dimensional and intervals as opposed to one-dimensional temporal regions.

The current definitions are still correct, but would be more precisely defined in terms of instants and intervals.

**Comment by cameronmore** [comment]
The alternative labels for these classes now read 'Zero-Dimensional Temporal Region Identifier' and 'One-Dimensional Temporal Region Identifier,' does that address this issue?

**Comment by alanruttenberg** [comment]
Not sure. It seems the intention of the terms was to identify instants and intervals so I would have thought that the logical definitions would be changed to use the appropriate terms.
There's also the usual problem with the classification of terms directly below one of the directive/descriptive etc terms in that the same form might be used differently. The appropriate thing, in my view, is to use the appropriate relation on the instance and let the instance be automatically classified into one of these classes.

**Comment by neilotte** [comment]
This issue has been addressed. Recommend opening in the discussion forum a related thread on synonyms.

**Comment by alanruttenberg** [comment]
how has it been addressed?

**Comment by neilotte** [comment]
@alanruttenberg I think your wording through @cameronmore and I off. It sounds like you are recommending:

The definition of Temporal Instant Identifier be changed to: 

`A Temporal Region Identifier that designates some Temporal Instant.
`
The definition of Temporal Region Identifer be changed to:

`'A Temporal Region Identifier that designates some Temporal Interval.`

Can you confirm?

The other matter regarding the broader strategy of taxonomizing ICEs seems appropriate for a different thread.

**Comment by alanruttenberg** [comment]
Yes, and the axioms as well. That seems to match the intent.
