### ISSUE TITLE
Proposal for the term "Filter"

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#142]
My initial read was as a filter for material things as opposed to an optical filter, but I think the term could include both. I wanted to verify that interpretation. If optical filters are included, to help document could an example be included in the comment or as example of usage? 

In addition, I propose factoring this as a 'filter function' and making the artifacts a defined class. 

Assuming this factoring, I'd propose the definition:

>Filter function: "function of an artifact, realized in a process where entities enter it but the portion that are of a specified type or which have specified properties constitute the majority of what passes through it"

>Filter: "any artifact that bears a filter function"

Rationale for changes in wording: 
1. The reference to a system isn't essential as it isn't clear what additional inference that might bring. 
1. As a matter of consistency of definitions, it doesn't seem that reference to being part of a system is consistently made in analogous items, for example flywheel or fuel system. In the case of fuel system there is reference to a propulsion system but not to a system that includes both the fuel system and propulsion system.
1. Mention of separation seems redundant and may suggest mechanism. For example in a resonance filter it's not necessary that there is a separation into parts of the original. The portion not passed might be transduced.
1. The reason for the "majority of" language is that most filters aren't perfect. 

Rationale for factoring: Consider a filter that both filters some type of thing and limits the amount of that thing. Limiting isn't filtering in that there's no specific property that is being selected. So, the limiting is one function and the filtering another and artifacts can have one or both functions. If we represented the artifact only we would land up with multiple asserted polyhierarchy.

I am representing optical filters in my work and I would do this defining subclasses of filter function then adding additional defined classes.

**Comment by alanruttenberg** [comment]
bump. This seems like an easy and I would think uncontroversial change. Should I submit a PR?

**Comment by mark-jensen** [comment]
@alanruttenberg Please do. Make the PR on develop, not master.

**Comment by cameronmore** [comment]
@alanruttenberg This would be a good change for 2.0.  I would like to suggest the following revised language for the definitions:

Filter = A Material Artifact which bears an Artifact Function.

Filter Function = An Artifact Function that is realized in a process where entities of a specific type or which have specified properties enter it or pass through it.

**Comment by alanruttenberg** [comment]
Should be Filter: A Material Artifact that bears a **Filter Function**

Also see [That vs Which](https://www.merriam-webster.com/grammar/when-to-use-that-and-which)
