### ISSUE TITLE
Duplicate relations CCO/IAO included in CCO

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#146]
Hi,
I was browsing annotation properties and saw that there are two versions, one from CCO and one from IAO, of the following 

- term editor
- definition source
- definition
- elucidation
- example of usage

There are other IAO properties as well, including one unlabeled one IAO_0000114 (has curation status)

Some of these are brought in by BFO, but most ROimport. FYI no OBO annotation properties are used in BFO-2020, so the ones to attend to are the ones brought in by RO. My suggestion is, to the extent that RO relations are used, that the file with the RO relations have all the IAO metadata properties removed, as these are already defined in CCO and might cause confusion, particularly the same-named ones. Use them or lose them...

It's worth considering using some of the SKOS properties in favor of the CCO ones when they mean the same thing. Some relevant ones would be

- skos:definition (vs cco:definition)
- skos:example  (vs cco:example_of_usage)
- skos:scope note (vs cco:editor note)

**Comment by cameronmore** [comment]
As discussed elsewhere, we plan to move to skos properties and follow community practices.
