### ISSUE TITLE
Does CCO contradict an example-of-usage annotation for object property RO_0000059 (concretizes)?

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#149]
One of the example-of-usage annotations for RO_0000059 (concretizes) is:

> An investigator reads a protocol and forms a plan to carry out an assay. The plan is a realizable entity (a specifically dependent continuant) that concretizes the protocol (a generically dependent continuant), and both depend on the investigator (an independent continuant). The plan is then realized by the assay (a process).

In CCO, Plan (class CCO_0005057) is a generically dependent continuant. Is this class different from the intended meaning of "plan" in the OBO relation ontology? If so, I recommend adding an annotation explaining the distinction.

**Comment by cameronmore** [comment]
Given the switch away from RO, does this issue seem to be resolved?

**Comment by mark-jensen** [comment]
No longer relevant. But yes, OBI makes a distinction between the GDC 'Plan Specification' and RE 'Plan', which is concretized in one's brain. CCO's 'Plan' mirrors OBIs 'Plan Specification'.
