### ISSUE TITLE
Definition of InfrastructureRole

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#150]
An individual of class Infrastructure must bear an InfrastructureRole. The definition of class InfrastructureRole is:

> A Role that inheres in facilities and systems in virture of their being necessary for the economy of a geopolitical region to function

Aside from "virtue" being misspelled, constraining Infrastructure to economic issues of a geopolitical region seems restrictive. My company has infrastructure, but I do not claim my company's operations are necessary for the economy of the US to function. Nor is all of its infrastructure necessary. Some is merely convenient.

Does CCO deliberately restrict infrastructure to this rather large-scale definition?

**Comment by mark-jensen** [comment]
@swartik We are revising our representation of infrastructure. A new term is added for Infrastructure Element, change of defs and labels, relocating the hierarchy. Your concerns re the overly restrictive definition are addressed. They can be previewed on this [branch](https://github.com/CommonCoreOntology/CommonCoreOntologies/tree/infrastructure-redo). Appreciate any feedback.

**Comment by swartik** [comment]
@mark-jensen The changes on that branch will definitely accommodate my concept of infrastructure better than the current official CCO elements. Some quick feedback:

1. I'm wrapping my mind around "Infrastructure System" vs. "Infrastructure". Is the intent to emphasize that some element is part of infrastructure, and that infrastructure elements work together?  That a router, say, is not by itself infrastructure but is part of some telecommunication infrastructure? 
2. If that's the case, did you consider making Infrastructure System a subclass of object aggregate?
3. Having looked at definitions for infrastructure in Merriam-Webster and the OED, I can see justifications for both Infrastructure System and Infrastructure as the class name.
4. Infrastructure Element's definition says it's an independent continuant that bears one or more functions. The class is equivalent to something that bears an Infrastructure Role. If the definition is correct, should Infrastructure Role actually be Infrastructure Function, a subclass of function or maybe Artifact Function?
5. An Infrastructure Element is likely to require temporal qualification. My work computer is part of my company's infrastructure until they surplus it, at which time I'll take it home and connect it to my personal network infrastructure.
6. Is Infrastructure Element equivalent to (using Manchester-like syntax) `'continuant part of at some time' some 'Infrastructure System'`? That would be a useful equivalence axiom.

**Comment by cameronmore** [comment]
@swartik since this change has been merged, may this issue be closed?
