### ISSUE TITLE
'has process part' in BFO 2020

### ISSUE THREAD

**Issue by ameliakahn** [CommonCoreOntology/CommonCoreOntologies#152]
'has process part' may be redundant in BFO 2020.  BFO 2020 includes 'has occurent part', which is not coextential with 'has process part', but covers most of the same cases.  'has occurrent part' is more general than 'has process part' in that it can have any occurrents as relata, not only processes. 

The primary role that 'has process part' plays seems to be specifying the a process' process profiles.  'has occurrent part' is more general than 'has process part', and can have temporal regions or spatiotemporal regions as relata.   If 'has process part' were deprecated, we would need to make sure that only processes, not other occurrents, have process profiles as parts. We could do this pretty straightforwardly by making Process Profile SubclassOf 'occurent part of' some Process.  

Another option is to model process profiles differently, without 'has process part'.  The BFO 2020 Reference Document (though not its releases) includes a 'process profile of' object property, which could be used to connect processes to their process profiles.

**Comment by johnbeve** [comment]
@ameliakahn @jonathanvajda What exactly is the _issue_ being raised here?

**Comment by neilotte** [comment]
Closing this issue.
