### ISSUE TITLE
Information Bearing Artifact vs. Information Bearing Entity

### ISSUE THREAD

**Issue by PR0CK0** [CommonCoreOntology/CommonCoreOntologies#154]
Information Bearing Artifact is a sub-class of Artifact, which is a subclass of Object; defined in CCO/ArtifactOntology.
Information Bearing Entity is a sub-class of Object; defined in CCO/InformationEntityOntology.
Artifact is a sibling class to Information Bearing Entity.

Their use is confusing because both have the same prescription, that "is carrier of some Information Content Entity".

How is one to distinguish between these and how are they meant to be used? 

Is the difference that an Information Bearing Artifact is _designed_ to bear information, whereas an Information Bearing Entity is naturally or unintentionally bearing some information?

**Comment by mark-jensen** [comment]
Yes, you are on the right track. A bearing entity doesn't have to be an artifact, the only requirement is that it carries information. Eg., using a stick to write 'SOS' in the sand on a beach. The sand is not an artifact. Bearing artifacts are designed with the primary function of carrying information in some way. Eg., chalkboards, paper, hard drives.

All bearing artifacts are also (via inference) bearing entities, but not vice versa.

**Comment by PR0CK0** [comment]
> Yes, you are on the right track. A bearing entity doesn't have to be an artifact, the only requirement is that it carries information. Eg., using a stick to write 'SOS' in the sand on a beach. The sand is not an artifact. Bearing artifacts are designed with the primary function of carrying information in some way. Eg., chalkboards, paper, hard drives.
> 
> All bearing artifacts are also (via inference) bearing entities, but not vice versa.

Thank you very much. That makes a lot of sense.
