### ISSUE TITLE
What happened to bearer-of subproperties?

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#156]
The version of BFO on the master branch, which @mark-jensen committed on 2021-03-01, has five subproperties of "bearer of" (RO_0000053).  The version of BFO on the bfo2020 branch, committed on 2021-4-23, has only one subproperty of the equivalently labeled property (BFO_0000196). Are there plans to add equivalents to the others (has role, has disposition, etc.)? Or were they deliberately removed?

**Comment by mark-jensen** [comment]
@swartik The change to using BFO2020 properties required dropping the overlapping RO ones. All of those subproperties were form RO, so we deliberately deleted them. There are no plans to add equivalents to the BFO2020 version of CCO. 

Are you using this version of CCO that imports BFO2020? If so, can you comment on how that's worked for you so far? Specifically I am curious what kind of troubles you have encountered using the new temporalized properties, as well as with updating or integrating data that uses the old ones from RO/ERO.

**Comment by swartik** [comment]
@mark-jensen Thanks for the information. Yes, we are using the version of CCO that imports BFO2020. We anticipate using some of the classes in DICO, which also uses that CCO/BFO combination. Even if we didn't plan to use DICO, temporalized relationships are important to us, so I would have argued for using them.

We aren't far enough along to have encountered troubles. Expect me to post more messages.

**Comment by neilotte** [comment]
@swartik One of the issues with the temporalized relations in BFO2020 is that it does not support the representation of nonrigid classes using equivalence axioms.
