### ISSUE TITLE
Deconflicting IBEs and ICEs

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#160]
Only ICEs can cco:represents, but a few definitions in CCO imply IBEs can represent. I recommend their definitions are adjusted to clarify that this is not the case: 

- cco:List is defined as 'An Information Bearing Artifact that **represents** an ordered sequence of values, where the same value may occur more than once.' 

- cco:CodeList is defined as 'A List that **represents** an ordered sequence of Information Bearing Entities that bear Code Identifiers.'

- cco:Chart is defined as 'An Image that is designed to **represent** an Information Content Entity by means of Written Symbols in order to convey that information in a readily understandable format.'

**Comment by mark-jensen** [comment]
@neilotte and @jonathanvajda We are currently in the process of reviewing several of the subclasses of ‘Information Bearing Artifact’, considering how to refactor where appropriate. If these classes end up with specific IBA counterparts, the defs will certainly be redone to properly reflect that they carry the thing that represents. Thanks!

**Comment by jonathanvajda** [comment]
This topic is of renewed interest on both fronts @mark-jensen. A partner of mine just found this same issue that Neil raised. I am also working with ontology working group where this IBE-ICE issue has been under discussion.

**Comment by neilotte** [comment]
@johnbeve May I ask you to look at this PR thread when you have a moment? 

https://github.com/CommonCoreOntology/CommonCoreOntologies/pull/319

**Comment by johnbeve** [comment]
@neilotte Comments in the #319 PR sir

**Comment by neilotte** [comment]
This issue was addressed in https://github.com/CommonCoreOntology/CommonCoreOntologies/pull/319 . Closing now.
