### ISSUE TITLE
Typo in rdfs:comment for classes GainOfDisposition and GainOfFunction

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#163]
In the bfo2020 branch, the rdfs:comment annotations for classes GainOfDisposition and GainOfFunction reference object property occurs_on. The property in BFO 2020 is BFO_0000199, with label "occupies temporal region".

**Comment by swartik** [comment]
@mark-jensen Yes, we are using BFO2020 and its properties. Fortunately for us there was no legacy work to migrate: we based all our work on BFO2020. So we haven't had any translation problems. As I noted in #156, I was surprised to discover that some RO properties had no analogy in BFO2020, but their lack only resulted in using higher-level properties: using `bearer of` rather than `has role`. I imagine we will start creating domain ontology-specific properties that reflect the roles we model. So far this has not been important.

In our rush to deliver a product, we are using "some" properties rather than "all" properties unless we are very, very certain a relationship will always hold. We are still prototyping, and are sending graph patterns to our developer, who figures out how to turn data into those patterns. As we work through examples, we may discover a need for an "all" property. At this stage, switching properties won't be a problem: we aren't accumulating data in triple stores yet. And we have not found a need for rigid classes, per @neilotte's comment.

Really, the main problem using the new properties is their longer labels. The diagrams I draw for documentation are larger than in the past. Good thing we're not restricted to 8 1/2 x 11 paper any more.

**Comment by neilotte** [comment]
This change has been merged into development. Closing issue.
