### ISSUE TITLE
Question about class hierarchy for change of specifically dependent continuant

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#164]
In BFO,

    realizable entity
    |
    +- disposition
       |
       +- function

In CCO,

    Decrease of Realizable Entity
    |
    +- Decrease of Disposition
         |
         +- Decrease of Function

    Increase of Realizable Entity
    |
    +- Increase of Disposition
    |
    +- Increase of Function

    Loss of Realizable Entity
    |
    +- Loss of Disposition
    |
    +- Loss of Function

    Gain of Realizable Entity
    |
    +- Gain of Disposition
         |
         + Gain of Function

Why is change of Function sometimes a subclass of change of Disposition and sometimes not?

**Comment by mark-jensen** [comment]
@swartik This is a mistake. Thanks for the catch. However, in the next release, most of these classes will be deprecated. During a refactoring of 'stasis' and 'change' they were found to be overly redundant. Please see [here](https://github.com/CommonCoreOntology/CommonCoreOntologies/wiki/Proposed-revisions-to-Stasis-and-Change-Hierarchies) for discussion and also the [branch](https://github.com/CommonCoreOntology/CommonCoreOntologies/compare/stasis-change) that implements those changes.

**Comment by swartik** [comment]
@mark-jensen Thanks for letting me know. Is there a planned date for merging the `stasis-change` branch?

**Comment by mark-jensen** [comment]
@swartik Within the next month or two max.
