### ISSUE TITLE
OWL Profile a concern?

### ISSUE THREAD

**Issue by dlutz2** [CommonCoreOntology/CommonCoreOntologies#17]
Not sure if the OWL profile of CCO is of interest but a few things showed up as part of our inferencing experiments with CCO. 

CCO has two axioms that cause it to be more than OWL-DL (which may/should cause a DL reasoner to ignore them) :

- SubClassOf(<cco:SolarPanelSystem> ObjectMinCardinality(1 <ro:has_part> <cco:SolarPanel>)) 
- SubClassOf(<cco:SolarPanelSystem> ObjectMinCardinality(0 <ro:has_part> <cco:SecondaryCellElectricBattery>)) 

These are beyond OWL-DL because ro:has_part is non-simple (I think).

The first one could be re-written (and bring it into OWL-DL profile) as
- SubClassOf(<cco:SolarPanelSystem> ObjectSomeValuesFrom(<ro:has_part> <cco:SolarPanel>)) 

I'm not sure if the second can be written within OWL-DL but it is a not actually a restriction anyway since having 0-n batteries will always be true for any class (tautology) , thus a reasoner ignoring this wouldn't be an issue. (Although asking Protege to explain this axiom causes it to generate a very large number (1,000s) of justifications (all useless) since any axiom can be used to justify a tautology.

**Comment by mark-jensen** [comment]
We don't currently validate the ontologies wrt any of the OWL profiles. But this is helpful in that we should be aware of how certain axioms affect reasoning applications. I agree that asserting min cardinality 0 is not informative. 

This has me wondering: 
I am pretty sure asserting min cardinality of 1 can be accomplished with a standard existential restriction.

Eg-
SubClassOf(cco:SolarPanelSystem ObjectMinCardinality(1 ro:has_part cco:SolarPanel))
is equivalent to
SubClassOf(cco:SolarPanelSystem ObjectSomeValuesFrom(ro:has_part cco:SolarPanel))

Would use of the latter be valid in DL despite `has_part` being non-simple?

**Comment by dlutz2** [comment]
Yes, I believe the rewrite to SomeValuesFrom is OWL-DL even if the property is non-simple. The DL constraint seems to only apply to the use of non-simple properties in cardinality restrictions. 

Also, I have been thinking about the min cardinality 0. It definitely has no logical implications but the statement that a Solar Panel System might have a battery(ies) is informative to a human because it highlights the possibility.  Doesn't seem to be any way to say this within a description logic ( kind of guessing here)

I'll go ahead and close this as resolved. 
Thanks for the info. I am just getting into CCO  in detail, in prep for a BFO/CCO based project.

**Comment by swartik** [comment]
Not only is ObjectSomeValuesFrom valid for non-simple properties (see [here](https://www.w3.org/TR/owl-syntax/#Global_Restrictions_on_Axioms_in_OWL_2_DL) for details) reasoners I've used process it much faster than ObjectMinCardinality, irrespective of whether the property is simple.

**Comment by APCox** [comment]
Yes, the purpose of the "min cardinality 0" axioms is/was to be informative to the human user.
We have decided, in this case at least, to prioritize compliance with OWL-DL over human benefits - especially since we can easily include the content of these axioms in a comment or other annotation. Hence, the 1.1 version of the CCO will/should be OWL-DL compliant.

Thanks for the useful discussion!

**Comment by dlutz2** [comment]
Thanks, looking forward to CCO 1.1
BTW, do you have a nominal date for 1.1? I have a few comments/suggestions. I am currently building an ontology on top of CCO and knowing what changes/additions to expect would be useful.
