### ISSUE TITLE
Two comments and a question about cco:Agent

### ISSUE THREAD

**Issue by avsculley** [CommonCoreOntology/CommonCoreOntologies#175]
cco:Agent =def. "A Material Entity that is capable of performing Planned Acts"

1) There are material entities capable of performing one planned act, which are agents, but which are not on this definition due to the pluralizing of 'acts'.

2) Mine sniffing rats are agents on this definition becasue they are capable of performing some planned act. This seems right. Are their wild counterparts agents? I think they are on this definition becasue the wild counterparts are just as capable of performing planned acts. This seems like an unwanted consequence of the definition, though, becasue then every animal plausibly is capable of performing a planned act, and 'animal' would thus be a subclass of 'agent.'

3) What does it mean to be "capable of performing" some act? We want to count software agents, and not be so permissive as to allow that it means something like 'capable of participating in' (which would make all material entities agents).

**Comment by cameronmore** [comment]
The axiomatization of agency is permissive in CCO, which is a double edged sword perhaps. If the data captures the agency of rats, the ontology should be able to handle it. Machines on the assembly line of a car plant may be agents in the _parts_ of the manufacturing process, but certainly the car company is the agent in the entire act of manufacturing.

Open to hearing more about acts and plans, but I think the permissiveness of the ontology allows domain ontologies to make those sorts of decisions about the granularity of agency.
