### ISSUE TITLE
Clarification on cco:has_interest_in

### ISSUE THREAD

**Issue by avsculley** [CommonCoreOntology/CommonCoreOntologies#177]
Greetings,

>has_interest_in = A relation between an entity and some process where the entity has an interest in that process.

The definition suggests the domain is 'entity.' Yet, the domain is 'Agent.'

Please clarify this seeming inconsistency. 

@DavidGLimbaugh 

All the best,
Alec Sculley

**Comment by DavidGLimbaugh** [comment]
Good catch. The domain is correct and the definition too broad. It has been clarified on a patch branch.

https://github.com/CommonCoreOntology/CommonCoreOntologies/tree/patchfixes042823
