### ISSUE TITLE
Inexact owl:equivalentClass for Action Prohibition, Action Permission, Action Requirement

### ISSUE THREAD

**Issue by avsculley** [CommonCoreOntology/CommonCoreOntologies#178]
Greetings,

It seems 'Action Prohibition', 'Action Permission,' and 'Action Requirement' are not exactly equivalent to their specified owl:equivalentClass.

Each is equal to 'Action Regulation' and prohibits/permits/requires some Process.

Seems each should be equal to 'Action Regulation' and prohibits/permits/requires some Act.

Please clarify this choice. Alternatively, I am happy to submit a PR.

All the best,
Alec Sculley

**Comment by cameronmore** [comment]
This raises a few issues. Permission, prohibition, and requirement may be abut Acts most of the time, but not all of the time, so it makes sense to move in the direction of permitting/requiring/prohibiting processes broadly.

To that end:
- [ ] The parent class should be changed in label and definition to "Process Regulation"
- [ ] The subclass labels and definitions changed
- [ ] The twelve object properties should be changed as well (six being modal properties)
- [ ] And an elucidation added to the parent class explaining the decision to move from Act to Process.
