### ISSUE TITLE
Redundant axioms?

### ISSUE THREAD

**Issue by dlutz2** [CommonCoreOntology/CommonCoreOntologies#18]
Found 8 instance where there was both a simple subclass axiom as well as more Aristotelian equivalent classes axiom for the same class i.e.
 A is a B 
 A is a B that C's.

- AgentOntology
  - CivilOrganization
  - CommercialOrganization
- ArtifactOntology
  - ImagingInstrument
  - OpticalInstrument
  - PortionOfCoolant
  - WireReceiver
  - DishReceiver
  - PatchReceiver

Not sure about CCO policy/convention re this type of stuff. let me know if this is too much.

**Comment by swartik** [comment]
At least for some of those, I think the “A is a B that C’s” is necessary. These are equivalence axioms, not subclass axioms. Consider:



CivilOrganization ≡ cco:Organization and (cco:has_role some cco:CivilianRole)



Without the cco:Organization qualifier, a reasoner would infer that person with a civilian role is a civil organization.



I didn’t check all the property domains, so you may be right about other classes.

**Comment by dlutz2** [comment]
Sorry, should have been clearer. I intended to say that if you have both the subclass and the equivalence you don't need the subclass: 
A ≡ B that C's  implies A is a B.

By policy/convention you might always require a purely taxonomic backbone. Certainly for readability/comprehension have the explicit subclass axioms makes the overall structure clearer.

re: domain/ranges there were also about 30 domain/range axioms which can be inferred from other domain/range + inverse properties and sometimes a subproperty e.g.
ObjectPropertyRange( has_recipient Agent ) + InverseObjectProperties( has_recipient receives ) => ObjectPropertyDomain( receives Agent )

Removing these would drastically reduce the readability of the ontology even if they are redundant from an entailment perspective.

**Comment by mark-jensen** [comment]
Interesting discussion. Thanks.

We don't currently have a policy in place re redundant axioms. My guess is that we land more on the side of readability unless there is a performative concern. I have been told that certain applications cannot work with equivalency axioms, eg- treating the ontology as a graph, thus having the redundant subclass assertions may be helpful to some users.

**Comment by dlutz2** [comment]
Shouldn't be any performance issues, readability is a good thing. I'll close this as resolved.
