### ISSUE TITLE
owl:equivalentClass for Cause and Effect do not match definitions

### ISSUE THREAD

**Issue by avsculley** [CommonCoreOntology/CommonCoreOntologies#181]
Greetings,

The definitions of both cco:Cause and cco:Effect relate each to some process. However, the owl:equivalentClass for each relates each to some occurrent.

All the best,
Alec Sculley

**Comment by johnbeve** [comment]
@avsculley Can you open a pull request on the [develop branch](https://github.com/CommonCoreOntology/CommonCoreOntologies/tree/develop) and make the needed updates?

**Comment by avsculley** [comment]
Will do.
________________________________
