### ISSUE TITLE
clarification on 'organization member' subClassOf 

### ISSUE THREAD

**Issue by avsculley** [CommonCoreOntology/CommonCoreOntologies#182]
Greetings,

'Organization Member' has listed SubClassOf ('is affiliated with' some Organization). Yet, there seems not to be a corresponding parent class.

Can you clarify whether this should be the case? If so, why? If not, perhaps this should instead be a part of owl:equivalentClass of 'organization member'?

All the best,
Alec Sculley

**Comment by cameronmore** [comment]
The parent class is Person as described in the equivalence axiom.

**Comment by avsculley** [comment]
I don't think this was the case when I made this issue. There is a further issue with the equivalence axiom, but I'll make another issue about it.
