### ISSUE TITLE
Artifact Element

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#19]
1. There are a few classes like 'machine element', 'electronic component', 'vehicle frame part', etc that would benefit from a parent class 'Artifact Element', defined as 'an artifact that is designed to be part of an Artifact'. These various 'designed to be part of X' classes could then be refactored under this parent. 

For instance, this would be helpful for finding those weapon elements (e.g. triggers, barrels, shells, sights, etc) that are not weapons and may not be parts of weapons, and which otherwise are scattered throughout the artifact list. 
 
2. Other important subclasses of 'Artifact Element' could also be 'Infrastructure Element', where every instance of the class is designed to be part of some piece of infrastructure. E.g. ceiling, roof, truss, turret, gable, etc.. similarly for 'Vehicle Element' and 'Computer element'.

**Comment by BMandrick** [comment]
Components are important for targeting too.  Specifically when we are considering the parts (components) of e.g. a Bridge, Building, Weapon System, et. al.).  

See a modern bridge diagram here: 
 
https://user-images.githubusercontent.com/39055664/83150323-23efa500-a0c9-11ea-92af-af1527e023e4.png 

To make matters more confusing consider an old stone bridge where the Abutments, Piers, and Spans are arguably Fiat Objects. see: 

https://commons.wikimedia.org/wiki/File:Roman_bridge_at_Cangas_1_com.jpg

This also sounds similar to a problem in Systems Engineering Ontology too--isn't a car a System of Systems?

Regardless, we do need a class for 'Artifact Component' or 'Artifact Element'

**Comment by rorudn** [comment]
In version 1.3 roles have been added part, component, system and infrastructure.
