### ISSUE TITLE
Question about class Measurement Unit of Geocoordinate

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#195]
The definition of class Measurement Unit of Geocoordinate is:

    A Measurement Unit specifying the geospatial coordinates of a location.

That use of "the geospatial coordinates" rather than "a geospatial coordinate" makes me think a member of this class would a measurement unit that describes a lat/lon pair, or a lat/lon/alt triple. Is that the intent? If so, of what class would degrees-latitude be a member? Is it Measurement Unit of Length, measured from (say) the equator?

Or am I reading too much into the plural? Can class Measurement Unit of Geocoordinate include individuals denoting a one-dimensional measurement unit that can be used as part of expressing a geolocation?

**Comment by percivall** [comment]
Definitions from [ISO 19111-2019 Geographic information — Referencing by coordinates](https://www.iso.org/obp/ui/en/#iso:std:iso:19111:ed-3:v1:en)  

- coordinate
  - one of a sequence of numbers designating the position of a point
  - Note 1 to entry: In a spatial coordinate reference system, the coordinate numbers are qualified by units.
- coordinate system
  - set of mathematical rules for specifying how coordinates are to be assigned to points 
- coordinate reference system
  - coordinate system that is related to an object by a datum
  - Note 1 to entry: Geodetic and vertical datums are referred to as reference frames.
  - Note 2 to entry: For geodetic and vertical reference frames, the object will be the Earth. In planetary applications, geodetic and vertical reference frames may be applied to other celestial bodies.
- datum
  - parameter or set of parameters that realize the position of the origin, the scale, and the orientation of a coordinate system


For geographic coordinates:

- geodetic coordinate reference system
  - three-dimensional coordinate reference system based on a geodetic reference frame and having either a three-dimensional Cartesian or a spherical coordinate system
  - Note 1 to entry: In this document a coordinate reference system based on a geodetic reference frame and having an ellipsoidal coordinate system is geographic.
- geographic coordinate reference system
  - coordinate reference system that has a geodetic reference frame and an ellipsoidal coordinate system


ISO 19111 is also published as [OGC AS Topic 2: Referencing by Coordinates.](https://docs.ogc.org/as/18-005r4/18-005r4.html)

**Comment by cameronmore** [comment]
The Measurement Unit of Geo Coordinate is the _unit_ of measure, and not the value of the measurement; just as a Measurement Unit of Mass is gram.

A Measurement Information Content Entity may have the value "71.234", but the unit of measure is degrees and minutes. Moreover, the data properties 'has latitude' and 'has longitude' cover these measurements.

Degrees are currently angular measurement units, and not geo coordinate units. The proper representation of geo coordinate measurements and how to separate geometric degrees from geographic degrees warrants a larger discussion.

**Comment by alanruttenberg** [comment]
There's a strong push from my group to standardize on radians for latitude and longitude. I've done some work on geospatial reference systems and would be glad to have a meeting to compare notes.

**Comment by cameronmore** [comment]
@swartik has this issue been addressed, regarding the disambiguation of the measurement unit and the measurement value?

**Comment by alanruttenberg** [comment]
@cameronmore cam you point to the said disambiguation?

**Comment by cameronmore** [comment]
@alanruttenberg I think I misunderstood what @swartik wrote in the first place, my mistake

**Comment by swartik** [comment]
@cameronmore your 11/6/2023 reply answers my question.
