### ISSUE TITLE
Property has_spatial_part_of seems inconsistently named

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#2]
The geospatial ontology declares some object properties, including has_spatial_part_of. This property is the only one in the ro:has_part property hierarchy whose name ends with "_of". All the inverse properties in the ro:part_of hierarchy end with "_of". Would "has_spatial_part" be a better name for the property?

**Comment by rorudn** [comment]
Ouch. Yes it would. Will have to obsolete this property and then add a "new" one with the has_spatial_part" name.

**Comment by APCox** [comment]
Error fixed. Issue closed.
