### ISSUE TITLE
Property Damage

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#20]
Is there a preferred way for handling damage to property? I thought it might be under 'Act of Violence', but that class is more restrictive.

**Comment by rorudn** [comment]
The Common Core doesn't have a class that corresponds to the legal term of "Property Damage". If it were to be included then we'd have to at least consider adding every other criminal act. So instead we offer a stasis, "DamagedStasis" that is intended to be used as the effect of whatever act caused the property, or whatever else, to become so.

**Comment by neilotte** [comment]
Thanks Ron!
