### ISSUE TITLE
New Terms for CCO 1.5 Consideration

### ISSUE THREAD

**Issue by cameronmore** [CommonCoreOntology/CommonCoreOntologies#207]
In anticipation of the upcoming 1.5 release which will sync to the BFO 2020 release, I want to put a list of terms and changes for consideration in one issue.

Terms:

- Odometer = def. An Information Bearing Artifact that is designed to bear some Information Content Entity that **measures the distance of some spatial region that was the location of some Act of Location Change**. OR a simpler version: An IBA that is designed to bear some ICE that **measures the distance an entity has traveled**. An Odometer bears a Distance Measurement Artifact Function.
- Mileage = def. A Distance Measurement Information Content Entity that measures distance in Miles. (looking for definition suggestions!).
- VehicleLicensePlate = def. A One-Dimensional (or Three?) Barcode that is designed to carry an ICE about the registration and/or legal status of the vehicle to which it is attached."
- WorkShift = def. A One-Dimensional Temporal Region during which a person performs tasks and acts in accordance with some contract or employment agreement.

Other changes:

- Make is_tokenized_by a data property. I am not confident others will agree, not sure if I agree, but I want to ask for thoughts. I know a number of ontologies are using it already, and I think we should thinking about doubling down. Right now it's an annotation property. Happy to push this issue down the line to a later release, but just start the conversation.
- CCO curate process profile. This is a hot button topic right now, so I'm happy to push this off to a later release, but I would be comfortable with CCO curating process profile, if and only if process profile can be clarified and vetted in the next few months.

Happy to amend any of these, change definitions, etc.

**Comment by cameronmore** [comment]
Good points. As I'm thinking about distance, I'm wondering if it's too general. Distance could be something like the distance between two points, 2D Distance, or the distance between things in a 3D space like the distance between cities on a road. Do we mean "extension in a spatial region" when we say distance? If so, we already have terms more clearly delineating one type of space from another. I would rather change the definition to say 'spatial region' rather than adding a class.

Distance can be displacement but displacement is not always distance, so they would be siblings in the hierarchy, not parent and child. Is displacement just distance in a 2D spatial region and distance the measurement of a 3D region?

Often when we talk about odometers measuring distance, we mean that the odometer measures the distance of the `cco:ThreeDimensionalPath` which is defined as `A Three-Dimensional Spatial Region that encompasses the spatial region through which some Object travels.` When we talk about geospatial distances, even if we think we're talking about straight lines, we mean the straight lines that bend around the curve of the earth.

All said, I like your comment and want feedback to keep the discussion going, those are just some of my immediate hesitations.

**Comment by cameronmore** [comment]
Talking with @mark-jensen , he noted that in modern cars, usually other sensors collect data that is used to calculate the mileage, and those sensors feed into other calculations as well (i.e. they are not purely odometer sensors).

He also pointed out that mileage is really just a Distance Measurement ICE that uses Miles as the Measurement Unit, so I'm thinking if there is a need to add it given we can handle it with those other two classes. @jonathanvajda

**Comment by jonathanvajda** [comment]
Hey Cameron,

Mark is right. I independently realized the design pattern for mileage
should work that way, but forgot to reply. It is good for confirmation!

All the best,
Jonathan Vajda
/dʒɒnɑθɑn vaɪdɑ/
