### ISSUE TITLE
Geomagnetic Reference System

### ISSUE THREAD

**Issue by cameronmore** [CommonCoreOntology/CommonCoreOntologies#212]
Although many geospatial systems use territorial north, planes and ships use magnetic north as their point of reference for direction, heading, etc. This is a terms proposal for the Information Entity Ontology:

```
cco:InternationalGeomagneticReferenceField rdf:type owl:NamedIndividual ;
                                           rdf:type cco:GeospatialCoordinateReferenceSystem ;
                                           rdfs:label "International Geomagnetic Reference Field" ;
                                           rdfs:comment "This global main field model provides magnetic field values for any location on Earth, e.g. for  navigational purposes (declination) or as a standard for core field subtraction for aeromagnetic surveys. An updated version is adopted by International Association of Geomagnetism and Aeronomy (IAGA) every 5 years)."
                                           rdfs:seeAlso "https://www.iaga-aiga.org/" .
```

Although using 'field' breaks the convention of using 'system,' I think it makes sense here since it's already an instance _of a system_ and this is the officially recognized subject-matter-expert label. There is a paper which discusses the most recent adoption of the field, https://earth-planets-space.springeropen.com/articles/10.1186/s40623-020-01288-x

**Comment by mark-jensen** [comment]
@cameronmore What CCO class is this an instance of? Also, you may want to include the parenthetical source in the comment as a separate annotation. Not a def_source, but maybe a see_also. Or something like that

**Comment by neilotte** [comment]
@cameronmore This makes sense to me. In your PR, can I also recommend we list the paper you provide some as an additional citation for the instance? I'll mark this for 1.6 but if we can't get to it it can be relabeled for 2.0. thanks!

**Comment by neilotte** [comment]
Addressed by https://github.com/CommonCoreOntology/CommonCoreOntologies/pull/383/files
