### ISSUE TITLE
Term request: manages

### ISSUE THREAD

**Issue by PhiBabs935** [CommonCoreOntology/CommonCoreOntologies#214]
I think it may be beneficial to have a broad object property such as 'manages'.

Specifically, I think it would benefit a human resource related ontology project (e.g. human resources management) I am working on.

But this relation would also have broad application, as there are many Entities from all sorts of categories that can be managed:

e.g. finances, time, anger, waste, people, groups of people, organizations, etc.

Related, I am working on a Planned Act term, Act of Managing, from which to drill down to domain specific terms (e.g. Human Resource Management). My thinking was that this term, however it ends up getting labeled, would also be broad enough to cover all the different examples mentioned above. My first shot definition was therefore very generic (though, it is generalized from ways in which more specific types of managing, such as organizational management, are described): 
"A Planned Act wherein some Agent directs, controls, or coordinates some Entity or Entities for the purpose of achieving some goal."

**Comment by swartik** [comment]
@PhiBabs935 I'm not sure I'd lump together all those kinds of managing. The Oxford English Dictionary has 12 definitions of "manage" as a transitive verb. It distinguishes between managing a person and managing a project.

**Comment by cameronmore** [comment]
I'm happy to help sort these things out. First thinking about it, we should compare 'manages' with other similar terms, like 'oversees' 'is responsible for' and 'directs'. Each of these has a slightly different spin to it. Would there be a desire to model these differences? A director might oversee an entire department,, might be responsible for its successes and blamed for its failures, but does not manage projects. We can also think about direct management and indirect management--my Project Manager directs my immediate project, but my department head coordinates the operations. If we can work out a design pattern, I think these could be interesting relations to add.

**Comment by jonathanvajda** [comment]
It looks like "supervises" (and its inverse, "is supervised by") is the relevant CCO relation here.

Definition: "A person p1 supervises a person p2 by virtue of p1 directing, managing, or overseeing p2."

But it looks like it is passing the buck, since there is no relation or class for "directing", "managing" or "overseeing"

**Comment by neilotte** [comment]
@PhiBabs935 See @jonathanvajda 's response. Since this looks like the relevant relation you're looking for, I'm closing this issue. If it is not and you would recommend a different course of action, please reply in and we can re-open. Thanks!
