### ISSUE TITLE
Center of Mass as "zero-dimensional spatial region"

### ISSUE THREAD

**Issue by superlee1** [CommonCoreOntology/CommonCoreOntologies#219]
In #BFO2-Reference, p46: "_Object boundaries and sites_ are distinguished from the _spatial regions_  which they occupy at any given time as follows: (1) Object boundaries and sites move when their material host moves, and they change shape or size when their material host changes shape or size." 
The center of mass of some plasticine will move when that piece of plasticine  changes its shape, e.g., from sphere-like to a cubic whose extend is larger than two times of the sphere radius. Therefore, the center of mass should not be a sub class of spatial region which is at rest relative to a coordinate system.

**Comment by mark-jensen** [comment]
@superlee1  This isn't a question for CCO developers, but rather those for BFO. 
Please repost it either on the tracker at [BFO2020](https://github.com/BFO-ontology/BFO-2020) or orignal [BFO](https://github.com/BFO-ontology/BFO). Thanks.
