### ISSUE TITLE
preceded_by have stasis and process aggregate as domain and range

### ISSUE THREAD

**Issue by daltontc** [CommonCoreOntology/CommonCoreOntologies#22]
Currently preceded_by only allows usage with processes. I am requesting that we change the domain and range to include stasis and process aggregate in order to have a more generalized preceded_by to work with more use cases.

**Comment by mark-jensen** [comment]
`preceded_by` and `precedes` are not CCO terms. They are from the [Relation Ontology](http://www.ontobee.org/ontology/RO). Therefore we can't modify their definitions.

However, in the old version of RO that CCO is currently importing, there are no domain and range restrictions asserted for either property. Despite use of 'process' in the textual definition, you can use them to link instances of `process aggregate`. 

Important to note: In the new version of RO, the textual definitions have changed, and the domain and ranges are now explicitly asserted as `occurrent`. We are in the process of updating CCO to use a subset of the newest version of RO, which will be available in a forthcoming release.
