### ISSUE TITLE
Make cco:acronym a sub-property of skos:altLabel

### ISSUE THREAD

**Issue by johnbeve** [CommonCoreOntology/CommonCoreOntologies#224]
During the one-off Annotation meeting on 12-15-23, consensus was reached that (see "Annotation-Discussion-12-15" minutes on TRMC):
- either skos:altLabel or cco:acronym will be used for all acronyms
- cco:acronym will be made a sub-property of skos:altLabel

To be updated in the next release of CCO.

**Comment by mark-jensen** [comment]
Is the plan to deprecate cco:alternative_label? Thus also making cco:doctrinal_label a sub of the skos property?

**Comment by johnbeve** [comment]
@mark-jensen  I'd be in favor of this; from the survey of use, CCO is the only ontology using cco:alternative_label; others use skos:altLabel.

**Comment by mark-jensen** [comment]
@johnbeve I agree. CCO should follow current usage rather than reinvent existing standards. Annotations are metadata, have a very slim semantics, I don't see a reason not to reuse SKOS or DC or follow Foundry recommendations here.

**Comment by cameronmore** [comment]
Would we like to aim to implement this for 1.6, 1.7, or 2.0?

**Comment by neilotte** [comment]
@cameronmore  I'd like to get to this one today. @APCox Any bandwidth? Otherwise, we can take this one.

**Comment by neilotte** [comment]
@mark-jensen I'd execute this, but perhaps you can give some deprecation guidance? I'm not familiar with the latest practices that CCO has followed.

**Comment by johnbeve** [comment]
Gentlemen, in the interest of agility, I propose we review PR #455 in the interest of closing this issue, but open another focused issue on deprecating cco:alternative_label. 

Any objections?

**Comment by neilotte** [comment]
@johnbeve #455 now merged. Your proposed new issue now at: https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/458 . Thanks!
