### ISSUE TITLE
Always include a BFO import

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#227]
AFAICT the only ontology that explicitly imports BFO is the extended relation ontology. If that doesn't happen to be imported when you open one of the component files then there are BFO ids displayed in Protege. Since they all use BFO, I think they should all explicitly import BFO.

**Comment by cameronmore** [comment]
I agree. If I'm deploying CCO in an application, I will have custom imports and slims, and further domain modules, etc, so including the import doesn't seem like it would cause build issues for those using the ontologies. If I'm using a CCO module, I'm not sure why I wouldn't want BFO as well.

**Comment by neilotte** [comment]
This issue appears to duplicate a matter raised on https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/255 . I will close this branch and track this request under the other branch for the 2.0 release.
