### ISSUE TITLE
Version of RO used in CC is no longer supported

### ISSUE THREAD

**Issue by cmungall** [CommonCoreOntology/CommonCoreOntologies#23]
Hi, 

The object properties here are no longer supported:
https://github.com/CommonCoreOntology/CommonCoreOntologies/blob/master/BFO%20Version/ro.owl

For more background see
https://github.com/oborel/obo-relations/wiki/DifferencesWithOldRO

Since 2010ish there has been a new RO, which overlaps a lot with your extended relations (not surprising, many are in BFO reference doc). I noted this on our tracker:
https://github.com/oborel/obo-relations/issues/254

Would you like to join one of our RO calls and/or mail list to discuss RO/CCO alignment?

**Comment by mark-jensen** [comment]
@cmungall  Hi Chris, thanks for following up. We are aware CC is using an outdated version of RO. In preparation for making the update, I recently went through and documented the differences between the current version of RO Core and the old version of RO we're using, as well noting overlap between CC ERO and the rest of RO. As you noted, some of that overlap derives from creating terms for properties that were then only proposed additions to RO, eg- `inheres in` / `bearer of`. 

We want to maintain alignment with RO, OBO in general, especially at the upper level. We've been working out options to make the update. Of course once we do, we need to have in place a protocol for handling mapping between CC projects that have old RO IRIs embedded in mappings and queries.

I think joining an upcoming call to discuss is a great idea.

**Comment by dlutz2** [comment]
I would also be happy to see a migration to RO Core. I am currently caught between a new ontology development (which would like to use BFO + RO Core) and building on current CCO.

**Comment by neilotte** [comment]
I'm in the same dilemma as @dlutz2. It would be very helpful to see reintegration with RO Core.

**Comment by mark-jensen** [comment]
Updating CCO to use RO Core is next in the queue. We have just finalized our plan to update how we maintain our two repositories so they are better aligned. This will allow us to push changes here more quickly, especially in response to user requests. Stay tuned!

**Comment by mark-jensen** [comment]
Closed with 21c54e7f1b221f57d7427f0d8031db2cbf74b5c3

**Comment by cmungall** [comment]
ExtendedRelationOntology.ttl:

```
<http://www.ontologyrepository.com/CommonCoreOntologies/Mid/ExtendedRelationOntology> rdf:type owl:Ontology ;
                                                                                       owl:imports <http://www.obofoundry.org/ro/ro.owl> ;
```

**Comment by mark-jensen** [comment]
@cmungall  make sure you're on the `versions` branch. Sorry for the confusion. See #34.

**Comment by cmungall** [comment]
got it, thanks
