### ISSUE TITLE
Delete suggestion that describes is functional

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#231]
The comment says:
> It is possible that this relation should be a functional property, that is for all x, y, z if x describes y and x describes z then y = z. For example, if a financial report x describes the quarterly results of a company y and that same financial report describes the quarterly results of a company z, then it should be inferred that companies y and z are the same. We refrained from classifying the relation as a functional property on the concern that descriptions are multifaceted and so consequently it may be that the same report would contain descriptions of multiple entities.

I don't think that the property is a functional relationship at all, and the comment will confuse. Consider a specification of the dimensions of some class of parts. For example the [this page about a tire model](https://www.discounttiredirect.com/buy-tires/michelin-defender-2/p/108547) discusses a class of tires with partial description "225 /65 R17 102H SL BSW".

That description describes *all* tires of the class.  It satisfies the definition in that the description is about some characteristics by which tires of that model can be recognized or visualized.

That's not even close to being functional. The example you give is a reasonable one but is much more an aspect of the kind of information entity than saying something about describes in general. It's a little like saying that it's possible that part of is functional because steering wheels are part of only one car.

**Comment by neilotte** [comment]
@alanruttenberg Agreed. @oliviahobai -- would you mind taking this one on? If not, assign to me.

**Comment by oliviahobai** [comment]
I don't mind, I made a pull request to delete the comment as Alan suggested originally.

**Comment by alanruttenberg** [comment]
Generally the issue is closed when the pull request is merged, and it's commit message should close the issue by saying "fixes #xxx"

**Comment by neilotte** [comment]
@alanruttenberg That is the process, but looks like the gun was jumped here. This PR is now merged in, however. See https://github.com/CommonCoreOntology/CommonCoreOntologies/tree/describesconfusing

**Comment by oliviahobai** [comment]
> Generally the issue is closed when the pull request is merged, and it's commit message should close the issue by saying "fixes #xxx"
> looks like the gun was jumped here. 

You're right, my apologies.
