### ISSUE TITLE
Definition of "government organization" too restrictive

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#233]
According to the definition of "government organization", to be a government organization, an organization must be responsible for _both_ the oversight of specific governmental functions _and_ the administration of those functions. But need oversight and administration go hand-in-hand? Might not one organization be responsible for the oversight of specific government functions while another organization is responsible for the administration of those functions? If so, neither organization could count as a government organization according to the current definition, and that seems to be a mistake.

**Comment by cameronmore** [comment]
This is a good catch, but I think the term 'and' is being used more colloquially here, not logically. But, we do not want to say 'or' and create such a strict disjunction.

**Comment by gregfowlerphd** [comment]
@cameronmore:

Your suggestion that 'and' is being used in a colloquial sense here is interesting. A few thoughts:
- At least initially, I'm skeptical that there is such a colloquial sense of 'and'. (If there were, I would have expected some pushback when I presented to my dad and stepmom--neither of whom is much of a logician--the definition of 'government organization' and my criticism of it, but instead they were both totally onboard. More importantly, I would have expected some pushback from logic students to the truth conditions for 'and' (much like their pushback to the truth conditions for 'or' and 'if-then', but I've never received any.) I'm open to being persuaded, however. Other examples of the alleged colloquial sense would be helpful.
- If there are multiple senses of 'and', then the definition is ambiguous. But not being ambiguous seems to be a desideratum of ontology definitions. Perhaps, then, if there are multiple senses, revisions to the definition are called for to disambiguate it?
- You said that we don't want to say 'or' because it would create a strict disjunction. But I worry that the colloquial sense of 'and' would have to be equivalent to such a disjunction to handle my counterexample, in which case it would seem that the definition is already using such a disjunction, but simply hiding it.

Let me end with a question related to the third thought: Given that other definitions in the Agent Ontology do use 'or', why would its use here be so problematic?

**Comment by cameronmore** [comment]
then we can make it 'and/or' and users will know that it's an inclusive disjunction. Some terms in the ontology use 'and/or', and some use 'or' to express the same thing logically.

**Comment by swartik** [comment]
The comments by @gregfowlerphd over the past two days lead me to ask about the chosen format for definitions in CCO and the scope of CCO.

It seems to me the ambiguities stem from CCO definitions' choice of words that do not obviously correspond to properties. In the case of Government Organization, the phrase:

    is responsible for the oversight and administration of specific governmental functions.

means (I think):

- A Government Organization is the active agent in at least one process that is either an oversight process, an administrative process, or both.
- The process has as participants a government function and a Government.
- The government function specifically depends on the Government.

The definition of Government Organization would be something like:

    An Organization that is part of a Government and is the active agent in at least one process that is either
    an Act of Oversight or an Act of Administration, and this process has as participants a Government Function
    and a Government, and the Government Function inheres in the Government.

I'm writing the definition to suggest individuals associated with a Government Organization, along with the object properties used to associate them. I'm also suggesting some classes that should be in CCO, in the sense that the current definition implies their need.

Certain BFO definitions are written this way. You'd need first order logic to express the definition formally, but it's still more precise than the current version.

All this leads me to ask two questions:

1. Many CCO definitions are less rigorous than BFO's. Was this a deliberate decision?
2. If a CCO definition contains a conceptual term that's not a class or an object property, is CCO incomplete?

**Comment by gregfowlerphd** [comment]
@cameronmore Yeah, I think changing 'and' to 'and/or' would be the best solution. (Though I haven't yet read the proposal by @swartik, so maybe I'll change my mind.)

**Comment by gregfowlerphd** [comment]
I've now read the proposed definition by @swartik. It seems like a much more drastic revision than is required in response to my counterexample, given the availability of the 'and/or' revision. (Though perhaps @swartik thinks there are other reasons to make such a drastic revision.)

**Comment by swartik** [comment]
@gregfowlerphd Well, I am not so much proposing a new definition as wondering why CCO definitions are, by and large, less precise than BFO definitions. I am also giving food for thought to everyone pondering the definition of a middle ontology.

**Comment by cameronmore** [comment]
@swartik certainly there's a lot of room for improvement. The industrial ontologies foundry has done good work making sure their terms are formally axiomatized and well-defined. Perhaps we should consider offering more formal axioms for certain important concepts in the common core, like artifact.

**Comment by gregfowlerphd** [comment]
@cameronmore: Since you've been opening pull requests to close many of my issues, I was wondering whether we'd determined how to resolve this one. I thought we had (the "and/or" option), but I'm not sure.

**Comment by cameronmore** [comment]
I did a search and there are only a few terms that use 'and/or' phrase. I think turning 'and' into 'or' would be fine, and I hope users would understand that this is an inclusive 'or' (not exclusive). The entire definition could be improved which is another option. But I don't have a strong opinion on how to fix this one.

**Comment by gregfowlerphd** [comment]
@cameronmore: I guess I'm inclined towards the option of changing 'and' to 'or'. The latter is often used in CCO (including in the Agent Ontology), and users are trusted to understand that an inclusive disjunction is intended.

**Comment by neilotte** [comment]
This PR has been merged. Closing issue.
