### ISSUE TITLE
Problems with definition of "educational organization"

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#234]
According to the current definition, an educational organization is an organization "whose purpose is to provide training or otherwise facilitate learning or the acquisition of knowledge, Skills, values, beliefs, or habits".

There's a problem here due to the phrase "whose purpose". Is this meant to convey that an educational organization must have a singular purpose, or is it instead intended to be compatible with such an organization having multiple purposes? At the very least, this should be clarified.

Either way of clarifying it might be problematic, however. If it is clarified in such a way that an educational organization must have a singular purpose, then it implies that private, for-profit colleges aren't educational organizations, since they have purposes unrelated to education (e.g., making a profit). And that implication seems incorrect.

On the other hand, if it is clarified in such a way that an educational organization may have multiple purposes, then it implies that certain religious organizations (e.g., the Southern Baptist Convention) are educational organizations, since one of their purposes is to facilitate the acquisition of values, beliefs, or habits (of a religious nature). And, again, that implication seems incorrect (though it may be more palatable than the implication that private, for-profit colleges aren't educational organizations).

**Comment by swartik** [comment]
@gregfowlerphd You might clarify the meaning by changing "whose purpose" to "whose ostensible purpose". Even for-profit institutions don't advertise they're only in it for the money.

**Comment by cameronmore** [comment]
Organizations may have multiple purposes, they may have primary purposes and secondary purposes that they hope to achieve while fulfilling the first. Hence, why we have not create more detailed representations of them.

Commercial Organization is an equivalence class such that other organizations may become commercial organizations if they bear a Commercial Role. So, an Education Organization may or may not bear that Commercial Role, just as a Service Provider like Verizon may bear a commercial role but a Waste Collection Service may not bear that role if it's created as a special non-profit service. So, this solves the commercial purpose issue, but may not be totally satisfactory for religious organizations.

**Comment by gregfowlerphd** [comment]
@cameronmore: Yeah, it's clear that the definition of 'organization' doesn't require an organization to have a singular purpose. But that's compatible with the definition of 'educational organization' requiring an educational organization to have a singular purpose. This is why I proposed that the current definition, which uses a phrase ('whose purpose') that might be taken to express such a requirement, be clarified. Perhaps 'whose purpose' could be changed to 'one of whose purposes'?

I agree, though, that this does nothing to resolve the issue that some religious organizations will count as educational organizations.

@swartik: Interesting proposal. I agree it might solve the problem involving private, for-profit colleges. However, I might prefer 'one of whose ostensible purposes' (see above for why), given that it seems that an educational organization might have multiple ostensible purposes.

As far as I can tell, though, the resulting definition would still be subject to the problem involving religious organizations.

**Comment by cameronmore** [comment]
Thinking about it more, groups of people and organizations are not artifacts, which we have defined as having clear functions. The notion of purpose is certainly not the same or as strict as the notion of function, and because these agents have agency, they can choose to change the purpose of their organization with no problem (so long as they agree and follow the rules which they themselves set). If we were using the term function here, we might get into difficult waters trying to say that organizations only have one function. But agents are organic and not as rigid, we should extend that same flexibility to the purposes that organizations dedicate themselves to.

**Comment by gregfowlerphd** [comment]
@cameronmore:

I agree with what you say about the distinction between purpose and function and about the flexibility of an organization's purposes. So it might be on the right track.

On the other hand, I'm not entirely clear on what you're proposing, so I'm not sure it's on the right track. One thing that gives me pause is when you say: "If we were using the term function here, we might get into difficult waters trying to say that organizations only have one function." I may be misreading you, but it sounds like you're here proposing defining organizations as having only one purpose. If so, I think that's on the wrong track: Doing so would simply have the (untoward) consequence that certain groups of agents we'd typically take to be organizations aren't organizations merely because those groups have more than one purpose.

(FWIW, at this point, my preferred response to the issues I raised about the definition of "educational organization" is to simply change "whose purpose" to "one of whose purposes" (or maybe to "whose purpose or one of whose purposes") so as to clarify that an educational organization needn't have a singular purpose. The resulting definition would still imply that certain religious organizations are educational organizations, but I'm not sure that's so bad.)

**Comment by cameronmore** [comment]
I'm only trying to say what you just said, 

> change "whose purpose" to "one of whose purposes" (or maybe to "whose purpose or one of whose purposes") 

I would agree with that for a few of these classes.

**Comment by gregfowlerphd** [comment]
@cameronmore: Oh, OK. Yeah, I definitely think that's on the right track, then. :)

**Comment by cameronmore** [comment]
"whose established purpose," "whose ostensible purpose,""whose initial purpose," "whose primary purpose," (I think saying "one of whose purposes' would be too weak) or perhaps something else? Or just add an elucidation on the parent class noting that organizations do not have to have only one purpose, or that 'purpose' is not intended to be totally exclusive of other functions?

**Comment by gregfowlerphd** [comment]
@cameronmore: One option you didn't consider was 'one of whose primary purposes'. You're probably right that 'one of whose purposes' is too weak, but I'm not sure the same is true of 'one of whose primary purposes'. What do you think?

(I do have some thoughts about the options you did provide, if you don't like the option I mentioned.)

**Comment by cameronmore** [comment]
Yeah 'one of whose primary' feels too weak, like it implies that an org may have multiple primary purposes but that conflicts with the notion of primary itself, just a personal intuition

**Comment by gregfowlerphd** [comment]
@cameronmore:

First, as far as 'one of whose primary purposes' goes, do you think 'main' or 'major' would work better in place of 'primary'? (I'd also like to push back, gently, against the idea that if something has a primary X, it can have only one primary X. Google reveals many instances of the phrases 'two primary purposes' and 'two primary goals', and dictionary.com illustrates the relevant sense of 'primary' with a case involving multiple primary Xs. That said, I suspect 'main' or 'major' are preferable to ‘primary’ anyway.)

Second, ‘whose established purpose’, ‘whose ostensible purpose’, and ‘whose initial purpose’ all seem to be subject to the same problem as ‘whose purpose’—namely, the resulting definition might mistakenly be taken to imply uniqueness of the relevant sort of purpose. Similarly for ‘whose primary purpose’, if I’m right that an organization can have multiple primary purposes. And if I’m wrong, then a definition with ‘whose primary purpose’ implies (I think mistakenly) that an organization with exactly two equally important purposes cannot be an educational organization.

Third, I think the other option you provided—adding an annotation—might work, but the annotation would need to be phrased and placed with care. The issue isn’t whether organizations are required to have only one purpose. (Given the definition and axioms for organization, it’s clear there’s no such requirement.) Rather, the issue is whether ‘whose purpose’ in the definition for educational organization implies (or might be mistakenly taken to imply) that organizations of that particular sort are subject to an additional such requirement.

(Perhaps an analogy would help here. Parents are not required to be male. But the correct definition for one of the subclasses of parent—namely, father—will imply that parents of that particular sort are so required.)

With this in mind, let’s consider the details of the annotation route. Since the issue is with ‘whose purpose’ and only two subclasses of organization have that phrase in their definitions, it seems preferable to place the annotation on those subclasses rather than on the parent class. As far as what the annotation should say, I think something like this might work for educational organization:

> The use of the phrase ‘whose purpose’ in the definition is not intended to imply uniqueness of purpose: An organization of this sort might also have other purposes, including non-educational ones.
