### ISSUE TITLE
Force Generating Function

### ISSUE THREAD

**Issue by cameronmore** [CommonCoreOntology/CommonCoreOntologies#238]
There is a need for a generic Force Generating Function which may have more specific sub classes, like pressure generating or thrust generating. A provisional definition is:

`An Artifact Function that is realized in the process of generating of some Force.`

**Comment by mark-jensen** [comment]
Isn't this just a function whose realization causes a process that has a force profile? Am I missing something?

**Comment by cameronmore** [comment]
It is, and if it's too specific and collapses too many semantics, then there's no need to add it.
