### ISSUE TITLE
Suggested change for Best Practices doc

### ISSUE THREAD

**Issue by cmungall** [CommonCoreOntology/CommonCoreOntologies#24]
Principle of Single Inheritance:

_This principle does not prohibit the use of subclass or equivalent class axioms whereby a class is defined to be a subclass or equivalent class of an anonymous class. The OWL language provides the means to express facts about entities using relations to other entities. For example, a fact such as “Automobile has_part some Engine” uses the has_part relation to relate each automobile to at least one engine. The semantics of this fact is that Automobile has been made a subclass of the anonymous class “thing having at least one engine as part”. The class is anonymous because it is not part of the asserted taxonomy. The set of subclass and equivalent class axioms forms the inferred taxonomy of an ontology. In this inferred taxonomy classes previously anonymous become explicit and the principle of single inheritance is no longer in force. For further details see: (Smith & Ceusters, 2010)_

This is a little confusing as it confuses assertion with namedClass v classExpression distinction.

If I assert "car SubClassOf has_part some engine" it's still an assertion, not inferred.

I think what you want to say is:

 1. Ontology editors should only assert one named superclass
 2. The inferred/released edition of the ontology may have multiple direct inferred superclasses. This will be especially common with compositional classes which form a lattice/polyhierarchy on reasoning

Note that I think 1 is a good engineering rule of thumb but would not elevate to a principle.

**Comment by johnbeve** [comment]
@mark-jensen @APCox @cmungall is right; that this passage is misleading. 

Are there plans to revise the [Best Practices](https://www.nist.gov/system/files/documents/2021/10/14/nist-ai-rfi-cubrc_inc_002.pdf) document? 
- If not, then perhaps an errata page can be created for issues like this one, and this issue be closed. 
- If so, then perhaps a note can be added to update the passage above during revisions, and this issue be closed.

**Comment by mark-jensen** [comment]
@cameronmore Why wouldn't we update the existing document rather than go through the effort of drafting an entirely new one? 

Please create a wiki page for recording needed changes, fixes, improvements, etc. for the current or next Best Practices doc. Make sure to add a link to this issue and any others that may be relevant to improving the doc. Also add the link to the wiki page in a comment here.

This issue should stay open until we decide whether to create a new one vs. update the existing one.

**Comment by johnbeve** [comment]
@cameronmore Did you create a wiki page for recording changes, etc. to documentation as @mark-jensen requested? 

@mark-jensen @APCox @neilotte I suggest we revise the existing best practice document. If you agree, when @cameronmore creates the wiki, we can close this and coordinate on the discussion board, documenting updates in the wiki. 
If you prefer we create new document, then we can follow the same strategy.

**Comment by johnbeve** [comment]
Wiki has been created [here](https://github.com/CommonCoreOntology/CommonCoreOntologies/wiki/Revision-of-Best-Practices-for-CCO); closing this issue.
