### ISSUE TITLE
Definitions of Communication Reception Artifact Function's subclasses are too broad

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#246]
Communication Reception Artifact Function has two subclasses, whose definitions read as follows:

> **Radio Communication Reception Artifact Function:** A Communication Reception Artifact Function that inheres in an Artifact that is capable of receiving information transmitted from another Artifact to which it is not connected by an electrical conductor.

> **Wired Communication Reception Artifact Function:** A Communication Reception Artifact Function that inheres in an Artifact that is capable of receiving information transmitted from another Artifact to which it is connected by an electrical conductor.

But consider an artifact that is capable of receiving information _both_ from artifacts to which it is not connected by an electrical conductor _and_ from artifacts to which it is so connected. (I don't think this is a far-fetched case. I wouldn't be surprised if there were such artifacts; in fact, I'd be surprised if there weren't.) Given the definitions above, this artifact's Radio Communication Reception Artifact Function is also a Wired Communication Reception Artifact Function and vice-versa, which is incorrect.

The obvious fix here is to modify the definitions so that they appeal to realization, as do other definitions of the subclasses of Artifact Function:

> **Radio Communication Reception Artifact Function:** A Communication Reception Artifact Function that is realized during events in which an Artifact receives information transmitted from another Artifact to which it is not connected by an electrical conductor.

> **Wired Communication Reception Artifact Function:** A Communication Reception Artifact Function that is realized during events in which an Artifact receives information transmitted from another Artifact to which it is connected by an electrical conductor.

**Comment by cameronmore** [comment]
Agree, these are good changes and I think your definitions here work well.

**Comment by gregfowlerphd** [comment]
Thanks, Cameron. :)
