### ISSUE TITLE
Definitions of Signal Detection Artifact Function and Signal Processing Artifact Function too broad

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#248]
Given the definition of Signal Detection Artifact Function, if an artifact is designed to discern between information-bearing patterns and random patterns, or noise, that distract from the information, then all of that artifact's Artifact Functions are Signal Detection Artifact Functions, which needn't be the case. Similar remarks apply in the case of Signal Processing Artifact Function.

The definitions could probably be fixed if they were revised to appeal to realization.

**Comment by cameronmore** [comment]
`Signal Detection Artifact Function = An Artifact Function that inheres in Artifacts that are designed to discern between information-bearing patterns and random patterns, or noise, that distract from the information.`

could be turned into:

Signal Detection Artifact Function = An Artifact Function that is realized in the process of discerning between information-bearing patterns and random patterns, or noise, that distract from the information`

And 

`Signal Processing Artifact Function = An Artifact Function that inheres in Artifacts that are designed to process or transfer information contained in signals.`

Turns into:

`Signal Processing Artifact Function = An Artifact Function that is realized in the process of transferring or processing information contained in signals.`

@mark-jensen where can I start working on some of these changes? On this issue and ones similar like [246](https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/246)

**Comment by gregfowlerphd** [comment]
@cameronmore: Your proposed definitions sound good, though I'd suggest some minor changes that would make them more similar to most other definitions of Artifact Function subclasses:

> **Signal Detection Artifact Function:** An Artifact Function that is realized in processes in which some Artifact is used to discern between information-bearing patterns and random patterns, or noise, that distract from the information.

> **Signal Processing Artifact Function:** An Artifact Function that is realized in processes in which some Artifact is used to process or transfer information contained in signals.

**Comment by cameronmore** [comment]
The ancestor class Artifact Function already covers the 'inheres in an artifact that' portion of the definition, so although I like your suggestion, I think it could be conciser, and the other definition (that have the same style) also don't have that 'inheres in artifact that' portion.

**Comment by gregfowlerphd** [comment]
@cameronmore: I'm not sure what you mean. The slightly changed versions of your proposed definitions that I suggested don't mention inherence at all.

**Comment by cameronmore** [comment]
Sorry, I meant that the 'in which some artifact is used to' portion of the definition isn't necessary, that's more of the definition of the process in which the artifact is employed

**Comment by gregfowlerphd** [comment]
@cameronmore: OK. Although I'd note that most of the other definitions of Artifact Function subclasses do contain the "in which some Artifact is used to" portion.

**Comment by neilotte** [comment]
An update has been merged into development in response to this issue. Closing.
