### ISSUE TITLE
Definition of ‘Life Support Artifact Function’ too broad

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#251]
The definition reads as follows:

> An Artifact Function that is realized during events in which an Artifact is used to enable an organism to continue living in a situation where death would otherwise occur.

Suppose this definition is correct. Then when a gun is in the appropriate circumstances (e.g., when it’s used to prevent an imminent murder), its characteristic function (i.e., to fire a bullet) is a life support artifact function.

This untoward consequence (and others like it) might be avoided with only minimal textual changes to the definition:

> An Artifact Function that is realized during events in which an Artifact that is designed to enable an organism to continue living in a situation where death would otherwise occur is used to do so.

However, more drastic changes might be called for (especially given that this revised definition differs in structure from those for the other subclasses of artifact function).

**Comment by swartik** [comment]
@gregfowlerphd, your definition is definitely an improvement. However, if it's going to describe an artifact designed for life support, I'd argue that CCO should have a "Life Support Artifact" class. Then the definition of Life Support Artifact Function could be:

    An Artifact Function that is realized during events in which an Agent uses a Life Support Artifact
    on an Organism.

My initial thought was to make Life Support Artifact a subclass of Medical Artifact, but Medical Artifact as currently defined is too narrow:

    A Material Artifact that is designed for diagnosing, treating, or preventing disease or disability.

It would need to be changed to "preventing disease, disability, or death." Then Life Support Artifact could be defined as:

    A Medical Artifact designed to enable an Organism to continue living in a situation where a Death might
    otherwise occur.

(Note the switch from "would" to might". A definition closer to the truth is something along the lines of "where medical professionals judge that death will occur without the use of said artifact.")

**Comment by cameronmore** [comment]
These seem like good changes.

**Comment by gregfowlerphd** [comment]
@swartik: While there might be room to quibble about the details, I think something like your proposal sounds good.

**Comment by cameronmore** [comment]
>An Artifact Function that is realized during events in which an Artifact is used to enable an organism to continue living in a situation where death would otherwise occur.

I think we can still save the current definition and specify that the function is born by material entities that act upon those organisms, not just any organism.

>An Artifact Function that is realized during events in which an Artifact materially affects an organism which enables an organism to continue living in a situation where death would otherwise occur.

This reduces the ambiguity @gregfowlerphd mentioned. Regarding medical artifact, I think @swartik ‘s change is a good improvement:

> A Material Artifact that is designed for diagnosing, treating, or preventing disease, disability, or death.

Regarding adding subclasses of medical artifacts, I worry that this encroaches into the domain level too much, and that a medical artifact ontology in the OBO community would be a better authority to create a taxonomy for those wide array of artifacts.

**Comment by gregfowlerphd** [comment]
@cameronmore: I think the revised definition avoids the counterexample I raised only if the second 'an organism' is changed to 'that organism'.
