### ISSUE TITLE
Definition of ‘Sound Pressure’ ambiguous

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#252]
There is a minor ambiguity in the definition. In particular, it is syntactically ambiguous between one reading in which the phrase ‘that is a local deviation from the ambient Pressure’ describes the pressure mentioned at the beginning and a second reading in which it describes the sound wave mentioned in the middle. This ambiguity can be resolved in favor of the first reading (which I take to be the intended one) by revising the definition as follows:

> A Pressure that is caused by a Sound Wave and is a local deviation from the ambient Pressure.

**Comment by neilotte** [comment]
The PR to address this issue has been merged into development. Closing issue.
