### ISSUE TITLE
Definitions of ‘Loudness’ and ‘Pitch’ suggest an unasserted subclass relation

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#254]
The definitions here read as follows:

> **Loudness:** A Sound Process Profile that is characterized by the amplitude, frequency and power of translated sound waves, typically on a continuum from soft to loud.

> **Pitch:** A Sound Process Profile that is characterized by the frequency of translated sound waves, typically on a continuum from low to high.

Given the first definition, every instance of loudness is a sound process profile that is characterized by the amplitude, frequency and power of translated sound waves. Hence, every instance of loudness is a sound process profile that is characterized by the frequency of translated sound waves and is thus (according to the second definition) an instance of pitch, making loudness a subclass of pitch.

I take it that this unasserted subclass relation is unintended and incorrect. Might it be avoided by adding ‘entirely’ before ‘by’ in the second definition?

**Comment by mark-jensen** [comment]
Great observation. I don't think we want Loudness to be a sub of Pitch. I think it's Loudness that is wrong.

https://byjus.com/physics/loudness-of-sound/

Loudness: A Sound Process Profile that is characterized by the amplitude and total energy of translated sound waves, typically on a continuum from soft to loud.

**Comment by gregfowlerphd** [comment]
Thanks, Mark. :) I just wish I hadn't assumed CCO had the basics right, so that I would have looked into the phenomena more like you did.

**Comment by neilotte** [comment]
An update has been merged into development in response to this issue. Closing.
