### ISSUE TITLE
Use of ‘describes’ in definitions of ‘Velocity’ and ‘Angular Velocity’

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#256]
According to the definition of ‘Velocity’, a velocity is a process profile--a subclass of occurrent--that describes something. However, according to the Information Entity Ontology, the domain of **describes** is information content entity, which is a subclass of generically dependent continuant. Hence, no process profile can describe anything, since no occurrent is a generically dependent continuant.

Similar considerations show that the use of ‘describes’ in the definition of ‘Angular Velocity’ is also problematic.

Perhaps this problem could be avoided by using ‘characterized’ rather than ‘describes’ (as do the definitions for many of the other subclasses of process profile)? The definitions would then become:

> **Velocity:** A Process Profile of an object's Motion that is characterized by its Speed and direction with respect to a frame of reference.

> **Angular Velocity:** A Velocity that is characterized by both the angular (i.e. rotational) Speed of an object and the Axis about which the object is Rotating.

(With respect to the second definition, however, I’m not sure whether it’s right to say that an angular velocity is _characterized_ by the relevant axis. What do y’all think?)

**Comment by cameronmore** [comment]
Without getting into a larger discussion of process profiles and how to write their definitions, this makes sense to me. It seems like 'consists of' would also work instead of 'characterized'.

**Comment by gregfowlerphd** [comment]
Thanks for your reply, @cameronmore. Good to hear you agree.

I worry about 'consists of', particular wrt the second definition. The phrase seems to indicate something like a compositional relationship, and it seems odd to me that an _occurrent_ like a velocity could be partially composed of an axis--which, after all, is a _continuant_ of the one-dimensional spatial region variety. (Something like this worry also lies behind the parenthetical remark at the end of my initial post, although I think it has less force in the 'characterized by' case.)

**Comment by mark-jensen** [comment]
@gregfowlerphd I agree use of 'characterized by' is the way to go. Please use the branch created for this issue to make changes to the defs for Velocity and Angular Velocity. You'll see the branch listed in the sidebar on the right under "Development". 

Additionally, please remove the parenthetical (i.e., rotational) from the def for Angular Velocity and add an alternative label for it "Rotational Velocity. 

When ready, please create a PR on 'develop' and tag @cameronmore to review. If not sure how to do this, please DM and I can help you.

**Comment by neilotte** [comment]
An update has been merged into development to address this recommendation. Closing.
