### ISSUE TITLE
Use of ‘instance of’ in ‘has member of located in’ definition and other ERO definitions

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#259]
[Sorry for the length; there's a lot to talk about.]

The definition of 'has member of located in' reads:

> An instance of an Object Aggregate 'has member of located in' an instance of some material entity if and only if every member of that Aggregate is located in the same instance of that material entity.

An initial (minor) issue here is the use of single quotation marks. Since these are not used in the other definitions, I doubt they should be present here.

The main problem I want to focus on, though, involves the use of ‘instance of’. (Note: ‘instance of’ is also used in many other definitions in ERO, but not all these uses are similarly problematic. I discuss this below.) Suppose X has member of located in Y. The definition then indicates that X is an instance of an object aggregate, A, and that Y is an instance of some material entity, M. However, object aggregates and material entities more generally don’t have instances because they aren’t classes (or universals), and hence the definition is unsatisfiable.

The same problem arises in the definitions of ‘process started by’, ‘affects’, ‘process starts’, ‘is temporal region of’, and ‘is affected by’, and a related one arises for ‘caused by’ and ‘is cause of’.

I think my preferred way to fix this problem would be by revising the definition of ‘has member of located in’ as follows

> An Object Aggregate has member of located in some material entity if and only if every member of that Aggregrate is located in that material entity.

and making similar changes to the other definitions mentioned above.

Worth noting that there are other definitions in ERO that unproblematically make use of ‘instance of’. For example:

> x aggregate_bearer_of y iff x is an instance of Object Aggregate and y is an instance of Specifically Dependent Continuant and z is an instance of Object, such that z bearer of y, and all other members of x are bearers of a unique instance of the same type as y.

Here, due to the lack of an article before ‘Object Aggregate’, that phrase can be taken to refer to the class of object aggregates rather than to a particular object aggregate (as in the ‘has member of located in’ case). (This, of course, suggests an alternative way to revise the problematic definitions.)

However, while its use in some definitions is unproblematic, I suspect it would be better if ERO didn’t use ‘instance of’ at all. For notice that none of the definitions for object properties in BFO use that phrase, nor do definitions from the other Common Core Ontologies. (As an example of the latter point, the definition for ICE begins with ‘A Generically Dependent Continuant’ rather than ‘An instance of Generically Dependent Continuant’.)

**Comment by mark-jensen** [comment]
Great catch @gregfowlerphd. I understand that some will read "instance of _an_ CLASS" as "instance of a instance of CLASS" 

I have been wanting to get all definitions for relations into the same format for some time now.  All should be something like: 

`x [relation label] y iff x instance of [label of domain class] and y instance of [label of range class], and [describe criteria for how x relates to y]

**Comment by gregfowlerphd** [comment]
Thanks very much, Mark. :)

I agree with you that having a standard format for the definitions would be preferable. Also, as I mentioned, it's the "an" before "Object Aggregrate" that causes the problem (as well as the "some" before "material entity"), so I think your proposed format is unproblematic. Applied to the current case, I believe it would result in the following:

> x has member of located in y iff x is an instance of Object Aggregate and y is an instance of Material Entity, and every member of x is located in y.

Is that right?

A couple of questions:

1. I passed over this in my original post, but does the definition capture the intended meaning of "has member of located in"? The relation label _sounds like_ it should pick out a relation that obtains between an object aggregate, A, and a material entity, M, just in case _at least one member_ of A is located in M. In contrast, the definition requires _every member_ of A to be so located for the relation to obtain.
2. Is there some reason to continue to use the "instance of" locution in the definitions, as in your proposed format? It seems to make the definitions longer, and perhaps more complicated, than necessary. (Moreover, as I noted, BFO seems to get away with not using it in its relation definitions, and it also is used in the other ontologies in the Common Core.) Why not the following standard format instead?:

> x [relation label] y iff x is a(n) [label of domain class] and y is a(n) [label of range class], and [describe criteria for how x relates to y]

Applied in the case of "occurs at" (whose definition currently uses "instance of"), this would result in:

> x occurs at y iff x is a Process and y is a Site, and x occurs in y.

**Comment by cameronmore** [comment]
@APCox in #127 has expressed similar concerns. I think that the label for this property could be altered to "all members of located in" and introduce another property "has some member of located in" so we can disambiguate the confusion between having at least one member located somewhere and having all members located somewhere.

I think 'instance of' makes things very clear and, although verbose, serves as a robust guide to those modeling or those who are not used to BFO-CCO. Although wordy, I think it shores up any potential confusion.

I am happy to start working on this in a branch, and will link it to this issue.

**Comment by gregfowlerphd** [comment]
@cameronmore: I definitely like your proposal to distinguish between **has all members of located in** and **has some member of located in**. I'm also glad that the definitions you've proposed for these object properties avoids the original issue I raised about object aggregates and material entities more generally not having instances by getting rid of the problematic 'an' and 'some'.

A couple of questions: First, you said you're 'happy to start working on this in a branch'. Just wondering what the 'this' is you're happy to start working on? Second, you provided some reasons to continue to employ 'instance of' in ERO object property definitions. I think I can see the appeal of these reasons. Do you think they also speak in favor of employing 'instance of' in class definitions in other CCO ontologies?
