### ISSUE TITLE
Artifacts and Functions

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#26]
I believe the general approach of CCO is to not require via a class axiom that every instance of an artifact class is the bearer of a function, in order to allow that broken or nonfunctioning instances of a particular artifact class might remain instances of that class. 

However, 'Vehicle' appears to have the subclass axiom:

'bearer of' some 'Conveyance Artifact Function'

Should this be removed?

**Comment by mark-jensen** [comment]
We are reconsidering how to use Artifact Functions in subclass axioms, if at all. 
For v1.1 [0838e2d] all axioms between Artifacts and their corresponding Functions were removed.
