### ISSUE TITLE
Lack of context in definition of ‘has object’

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#260]
The definition reads as follows:

> If p is a process and c is a continuant, then p has object c if and only if the c is part of the projected state that the agent intends to achieve by performing p.

Notice that the phrase ‘the agent’ appears out of the blue, as there is no agent mentioned earlier in the definition. Thus, it’s unclear to what agent that phrase is referring.

I think the definition can be easily revised to add the relevant context as follows:

> If p is a process and c is a continuant, then p has object c if and only if p is performed by an agent and c is part of the projected state that agent intends to achieve by performing p.

**Comment by cameronmore** [comment]
This seems like a good clarifying change.

**Comment by neilotte** [comment]
An update has been merged into development to address this recommendation. Closing issue.
