### ISSUE TITLE
Problems with definitions for subproperties of inheres in aggregate

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#261]
The final clause of all three definitions is the same: ‘such that x disposition_of_aggregate y’. In the case of **disposition of aggregate**, this makes the definition clearly circular. In the case of the other two subproperties, it makes no sense given the domains specified for those subproperties vs. that specified for **disposition of aggregate**.

I believe that in all three definitions, ‘disposition_of_aggregate’ should be replaced with ‘inheres_in_aggregate’.

**Comment by cameronmore** [comment]
I agree, this seems like an oversight

**Comment by cameronmore** [comment]
Merged into development, closing this issue.

**Comment by alanruttenberg** [comment]
Shouldn't this be a subproperty of inheres_in?

**Comment by gregfowlerphd** [comment]
@alanruttenberg: I don't believe it should be, contra @cameronmore. If **inheres in aggregate** were a subproperty of **inheres in**, then for any x and y, if x inheres in aggregate y, then x inheres in y. But according to the definition of 'inheres in aggregate', x inheres in aggregate y iff (i) x is an SDC and y is an OA, (ii) there is an Object z that's a member part of y and x inheres in z, and (iii) every other member part of y is a bearer of an SDC of the same type as x.* Now suppose A is an SDC and B is an OA such that A inheres in a member part of B and every other member part of B is a bearer of an SDC of the same type as A. Then, according to the definition, A inheres in aggregate B. Does it follow that A inheres in B? No, because inhering in a member part of an OA doesn't entail inhering in that OA. Thus, **inheres in aggregate** _isn't_ a subproperty of **inheres in**, since it's _not_ the case that for any x and y, if x inheres in aggregate y, then x inheres in y.

(That said, you might think that 'inheres in aggregate' isn't a particularly appropriate name for the object property so defined.)

*Or, at least, that's what I take the definition to be trying to say, though there are problems with it (as well as with the specified domain).

**Comment by alanruttenberg** [comment]
My bad you are right.

But yuck! Yes, the name is poorly chosen, and I would be interested in how this is used practically. No examples of use given. Trying to imagine: For role of aggregate it would mean that every member could independently realize the same (type of) role. I suppose that in my suggestion of a shared stewardship of a domain name, anyone in the group of agents in such a group has a "domain name manager" role so you could say "domain name manager role 1" inheres_in_aggregate <shared stewardship group>. Or for quality I guess you could define an aggregate of red things as quality_of_aggregate red-quality. Is that the intended use?

It's a hack for avoiding a relation to a class and so, in OWL, punning. Properly the relation would relate an sdc type to an aggregate  which would imply every member bears an sdc of that type. That would be cleaner than "of the same type". The inverse relation (easier to name) might be 'members bear an instance of' as in aggregate-of-red-things-1 'members bear an instance of' red-quality 

I assume the domain problem  you are referring to is that domain is SDC or GDC but definition says only SDC.

Yes, there is a problem with the definition in that "being of the same type" is trivially satisfied in that everything is an instance of entity and so "is the same type". Would need to say something that said that makes clear you have to be *all the same types*

It's temporally ambiguous as well, as instance-of is time indexed. So given the definition it could mean members bear instances of the same e.g. quality type at the same time, or at completely different times, or something in between.

**Comment by gregfowlerphd** [comment]
@alanruttenberg: Yeah, I'd definitely be interested in how it's used too. I wouldn't be surprised if folks used it in a way consistent with what 'inheres in aggregate' is naturally taken to mean (i.e., a range restriction on **inheres in**). Incidentally, Cameron and I are dealing with a similar issue over on #145.

The domain problem partially consists in the fact that the definition says only SDC but also of the fact that the domain of **inheres in** is SDC.

I agree with the problems with the definition you identified. Also:

- The use of variables is sloppy. 'z' appears out of the blue without any quantifier binding it.
- The definition never actually states that z is a member part of y.

I believe I'd planned on raising some of these issues with the definition but held off because Mark and I were going back and forth over the use of 'instance of' in object property definitions over in #259. (I was arguing that if class definitions could get away with not using 'instance of'--and instead using 'is'--object property definitions should too.)

**Comment by cameronmore** [comment]
I think I'll close this issue since the original issue was resolved, and I too mistook 'inheres in aggregate' as a subclass until I read the definition closer.
