### ISSUE TITLE
Misuse of temporally projects onto in definition of ‘is temporal region of’?

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#262]
The current definition is:

> x is_temporal_region_of y iff y is an instance of a process or process boundary and x is an instance of a temporal region, such that the duration of x temporally projects on y.

Notice the phrase ‘temporally projects on’. I take it this is intended to denote the same object property as BFO’s ‘temporally projects onto’? If so, the definition misuses that object property: In BFO, its domain and range are specified to be spatiotemporal region and temporal region, respectively, whereas here it’s taken to hold between the duration of a temporal region and a process or process boundary.

Since **is temporal region of** is supposed to be the inverse of **occupies temporal region**, and given the definition for the latter, the correct definition here would seem to be:

t is temporal region of p =Def t is a temporal region, p is a process or process boundary, and the spatiotemporal region occupied by p temporally projects onto t.

(Worth noting that the ‘t is a temporal region’ clause isn’t present in the definition of ‘occupies temporal region’. Should it be added there or removed here?)

**Comment by swartik** [comment]
@gregfowlerphd There's an editorial note in the definition of `is_temporal_region_of` saying it's in CCO for now because BFO doesn't have an inverse of "occupies temporal region" yet. Note the use of "for now" and "yet". The benefits of changing its CCO definition depend on the time frame in which it's expected to move to BFO.

**Comment by gregfowlerphd** [comment]
@swartik: That's reasonable. Though presumably whether it should be corrected depends also on the costs of doing so?

**Comment by cameronmore** [comment]
@gregfowlerphd does the following wording capture the desired change?

t is temporal region of p =def. t is a temporal region, p is a process or process boundary, and s is a spatiotemporal region such that s temporally projects onto t and p occupies spatiotemporal region s.

**Comment by alanruttenberg** [comment]
If it's just the inverse define it that way.
t is temporal region of p =def p occupies temporal region t 
OR
=def t is a temporal region and p is a process or process boundary and p occupies temporal region t

**Comment by gregfowlerphd** [comment]
@alanruttenberg: While I think it's perfectly fine to define inverse relations in the way you propose, that doesn't seem to be the way CCO typically does it. Might be worthwhile maintaining consistency here?

**Comment by alanruttenberg** [comment]
@gregfowlerphd I'd sooner have all the definitions change to this form. That's what's done in BFO. Writing longhand the inverse definitions gives unnecessary opportunity for errors.

**Comment by gregfowlerphd** [comment]
@alanruttenberg: That does seem better as a general policy.

**Comment by cameronmore** [comment]
I committed a change to correct this issue, but for 2.1, we can work on standardizing object property definitions and inverses
