### ISSUE TITLE
Change definition of 'Pointing Orientation'

### ISSUE THREAD

**Issue by cameronmore** [CommonCoreOntology/CommonCoreOntologies#264]
The current definition seems to capture something more specific than the term is designed to represent:

`Pointing Orientation = def. A Spatial Orientation of an Object in which one or more designated components of the Object are pointed toward a specified Target.`

I propose this altered definition:

`Pointing Orientation = def. A Spatial Orientation of an Material Entity in which one or more of its designated components are oriented toward a specified direction.`

**Comment by swartik** [comment]
@cameronmore, did you deliberately substitute "Direction" for "Orientation" in your altered definition?  I.e. are you proposing changing the label and the IRI too?

**Comment by cameronmore** [comment]
No, that's a mistake on my part, will edit

**Comment by neilotte** [comment]
An update has been merged into develop to address this thread. Closing.
