### ISSUE TITLE
UnParseable http URLs

### ISSUE THREAD

**Issue by deepananbu** [CommonCoreOntology/CommonCoreOntologies#265]
Hi everybody,

we are using a version of CCO at TIB Terminology service from http://www.ontologyrepository.com/CommonCoreOntologies/Mid/AllCoreOntology.

The above url is not parseable until it is changed to "https". It is the same for all the imports in the ontology file. 

Could you please update from http to https for the @base url and all the import urls?

Please let me know if any additional information is required.

Thanks,
Deepan A

**Comment by neilotte** [comment]
@deepananbu What software are you employing for the failing parse check?

**Comment by deepananbu** [comment]
@neilotte We are using OLS4 API to parse the ontology.

**Comment by neilotte** [comment]
Thanks @deepananbu. As it happens, we will be updating to https in a future update to CCO, which will follow the upcoming release. This should resolve this issue. 

Can you confirm the OLS4 API fails every ontology provided to it that does not use https? This seems like an unreasonable requirement, given that many OWL and RDF files use and will continue to use http. Just curious what you've found here.

**Comment by deepananbu** [comment]
@neilotte - OLS4 APi is not failing for all the http urls in ontologies. only for few ontologies we have this issue.

**Comment by neilotte** [comment]
@deepananbu I believe this issue can be closed with the decision to update IRIs coming in 2.0, but it is curious they're failing only for some but not all. Please reach out if there is a further issue here to be addressed.
