### ISSUE TITLE
Types vs. Classes in definitions for information classes

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#28]
This could be my weird ear, but I read 'Type' as a frequent synonym for 'Class' and I don't see a place in CCO where they are distinguished. This means sub-relations of 'is about' look like relations between classes rather than between instances. For instance: 

prescribes =def "For all types T1 and T2, if T1 prescribes T2, then there is some instance of T1, t1, that serves as a rule or guide to some instance of T2, t2 (if T2 is a type of bfo:Occurrent) or that serves as a model for some instance of T2, t2 (if T2 is a type of bfo:Continuant)."

The natural read is to take 'type' to mean 'class', particularly since only classes have instances. But then no instance is a class. 

If you agree this is mislead, perhaps we can work on a rephrase.

**Comment by mark-jensen** [comment]
Addressed in 44c635e
also #70
