### ISSUE TITLE
Issue with definition of ‘Communications Facility’

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#280]
According to the definition, a communications facility is ‘the bearer of functions realized in processes of receiving or transmitting information’. However, is it really the facility itself (which, per the definition for facility, is a building or campus) that bears these functions, or is it instead artifacts hosted by the facility? It would seem to be the latter.

Note that similar remarks apply to the definition of ‘Radio Relay Station’.

**Comment by cameronmore** [comment]
I see the problem, but I think levels of granularity are at work here. It is true that the facility isn't performing those functions from the vantage of the facility's contents, but at the level of populations, we do speak in this way. The X facility sends widgets to the Y facility which packages them, and sends them to facility Z to sell them. None of those facilities themselves are really performing those actions.

The definition can be improved certainly, happy to brainstorm.

**Comment by dlutz2** [comment]
There is a long tedious history of discussions on "Facility" which centered on the "building or campus" aspect but did not clearly include/exclude/relate the geographic (site), "campus" (which is not defined) or how to understand "at/in/part of" a facility.

**Comment by swartik** [comment]
Also, we could get into a long tedious discussion over questions like "If you temporarily move all the communications equipment out of a communications facility, is it a communications facility during the interval in which it has no communications equipment?"

I say this not to request the definition of Communications Facility be revised to address this question, but because I think CCO would benefit if its documentation had a statement somewhere expressing what @cameronmore said as a guiding principle.

**Comment by dlutz2** [comment]
By "what @cameronmore said as a guiding principle" did you mean something like "facilities are not actually performing these functions but we can speak, in both natural language and their ontological counterparts, as if they are"? Those are the types of principles/defintions the previously mentioned tedium was covering. Some of that made it into CCO 1.5 e.g.  `A Facility is a Material Artifact that is located in a Portion of Geosphere` to clarify the relation to "site" but whether a Facility is the building (and how does "is designed as" differ from "is" ) or the building is located at/in the Facility is still unclear.

**Comment by swartik** [comment]
I had in mind an explanation in one of the documents in the `documentation` folder, probably _An Overview of the Common Core Ontologies_. Something along the lines of:

> CCO definitions are phrased in terms of populations and common usage. For example, a Communications Facility does not actually communicate; rather, it contains Communication Instruments that bear communications functions and participate in Acts of Communication.  Definitions are kept simple by writing them as though the containing entity bears the function.

This does leave open the question of how a knowledge graph would model a Communications Facility and the Communication Instruments it contains. The answer is, I suppose, that it depends on how much granularity is important to your situation. Some  may choose to have the Communications Facility bear communications functions. Others may choose to have the Communications Facility contain Communication Instruments that bear communications functions. Or you could argue that a Communications Facility bears the role of containing Communication Instruments.

But I'm straying from my point. As always, there are any number of ways to model information, and I'm not taking a position on which is appropriate. I'm only trying to provide guidance on how to write definitions that don't overly constrain modelers.

**Comment by gregfowlerphd** [comment]
@cameronmore: Your levels of granularity suggestion is interesting. I'll think more about it and about how the definition might be revised. Also, I didn't mention this in my original post, but another reason I'm not entirely happy with the definition is that the definitions for all the other facility subclasses are put in terms of what the facility is designed for/to/as rather than what its functions are.

@dlutz2: I originally thought @cameronmore was suggesting that the facility really does bear the function, at some level of granularity (rather than merely that we can talk as though it does). However, having reread his comment in light of yours, I'm no longer sure. The last sentence of his first paragraph does suggest something more in line with your interpretation.

**Comment by cameronmore** [comment]
@gregfowlerphd standardizing the definitions is something we definitely want to do, so agree for sure on that point.

And without commenting on what I said earlier, suppose we do separate the machines and artifacts inside a building from the building itself. A facility that is designed to store materials (warehouse, storage facility) might actually bear that function of storing, of sheltering some material from the outside weather. But a factory does not bear a manufacturing function, but the machines inside that produce the widgets. The building, however, may have certain features that affords (`cco:Affordance`) agents to perform manufacturing activities easier than others (like having a wide open main floor, having a loading dock, etc.). Then, the building design does have some purpose, of affording certain agents to perform certain processes.

**Comment by cameronmore** [comment]
`Communication Facility = A Facility that is designed to support processes of receiving or transmitting information.`

`Radio Relay Station = A Communication Facility that is designed to support the receiving or transmitting of radio signals.`

Does this work?

**Comment by dlutz2** [comment]
The distinguishing feature of a "relay" station is the the reception and then retransmission of the received information. Most relay stations do not originate any information, just receive, amplify/improve and retransmit.

**Comment by cameronmore** [comment]
Good point, I was just trying to remove 'relay' from the definition of Radio **Relay** Station,

So, it becomes

`Radio Relay Station = A Communication Facility that is designed to support the receiving and re-transmitting of radio signals.`

**Comment by gregfowlerphd** [comment]
@cameronmore: The revised definition for Communications Facility seems to work. The second revised definition for Radio Relay Station (which takes into account the point raised by @dlutz2) also seems good, although I wonder whether 'processes of' should be added to make it more parallel to the Communications Facility def. The result would be:

> A Communications Facility that is designed to support processes of receiving and re-transmitting radio signals.

**Comment by cameronmore** [comment]
I think that works
