### ISSUE TITLE
Amount and Count Measurement ICE are not aligned

### ISSUE THREAD

**Issue by mark-jensen** [CommonCoreOntology/CommonCoreOntologies#282]
`Amount` is "A Quality that inheres in a bearer in virtue of the total, aggregate or sum of a number of discrete items or material the entity contains as parts."

`Count Measurement Information Content Entity` is "A Ratio Measurement Information Content Entity that is a measurement of the number of members of some aggregate."

Why isn't Count MICE about an Amount that inheres in an Object Aggregate?

**Comment by swartik** [comment]
@mark-jensen Your question is a good one, although it seems to me that it would affect how part/whole relationships are expressed, and sometimes oddly. I have two arms. To express that fact, do I need to say:

    :steves-body a :HumanBody ;
      :has-part :arm-aggregate .
    :arm-aggregate a bfo:ObjectAggregate ;
      :has-part :left-arm, right-arm ;
      cco:aggregate_has_quality :arm-amount .
    :arm-amount a cco:Amount .
    :arm-count a cco:CountMeasurementInformationContentEntity ;
      bfo:inheres_in :arm-aggregate ;
      bfo:is_concretized_by :arm-amount .

It seems strange to consider my arms an object aggregate. The definition of `Amount` refers to "total, aggregate, or sum". I think the definition of CountMICE should also use "total, aggregate, or sum".

**Comment by cameronmore** [comment]
To echo @swartik 's concern, we may want to count sites and other non-Objects.

This brings to mind a thought I've had regarding other types of aggregates, like do the members have to be `bfoObject`s? Given that `cco:Artifact` is a material entity, and earbuds are an artifact that have (at least) two discrete Objects, then "four pairs of ear buds" turn into "eight Objects that are members of an Object Aggregate," which is certainly not what we might want to count or care about. This doesn't mean the way forward is to create classes like Artifact Aggregate (I don't think personally), but just something to think about.

**Comment by neilotte** [comment]
@mark-jensen @cameronmore  May we close out this issue? As has been established, we may want to count things other than material stuff.

**Comment by neilotte** [comment]
@mark-jensen @cameronmore It seems this issue has been resolved. Please re-open if you feel there is more here. Thanks!
