### ISSUE TITLE
Interval terminology

### ISSUE THREAD

**Issue by ericatail** [CommonCoreOntology/CommonCoreOntologies#291]
Would it make sense in the interval documentation (such as 'interval contains') to tie the subject and the object to their appropriate INT1 and INT2?
"A Temporal Interval INT1 (subject) is disjoint with ..."  for example.

Thanks my friends!

-Eric

**Comment by ericatail** [comment]
And do we want the object to "interval contains" the subject.   Maybe I was just brought up the other way.

**Comment by ericatail** [comment]
Does this make sense?

I'm trying to map my customer's ontology to the BFO/CCO and I'm struggling to get the relationship polarities right.

**Comment by ericatail** [comment]
To be clear, I don't appear to have any way of knowing whether INT1 or INT2 is the subject or object of the _interval contains_ relation.

**Comment by ericatail** [comment]
And the same with the other temporal overlap relations - from what I recall.

**Comment by neilotte** [comment]
The definition reads at present: "A Temporal Interval INT2 **contains** some Temporal Interval INT1 iff there exist Temporal Instants inst1, inst2, inst3, and inst4 such that inst1 is the starting instant of INT1, inst2 is the ending instant of INT1, inst3 is the starting instant of INT2, inst4 is the ending instant of INT2, inst3 is before or identical to inst1, and inst2 is before or identical to inst4, but it is not the case that both inst3 is identical to inst1 and inst2 is identical to inst4." [bold for emphasis] 

I think the embolded 'contains should read 'interval contains' for clarity, but is certainly intended to holds between INT2 (the subject) to INT1 (the object). Please see a model conforming to the entities and relations specified in the definition. Hope this helps. 

<img width="633" alt="Screenshot 2024-08-04 at 10 34 28 PM" src="https://github.com/user-attachments/assets/e94792d6-e324-49bb-9ef1-ef9130d06b76">

**Comment by ericatail** [comment]
Hi Neil.  Thanks much for your kind reply.  Upon deeper inspections I see that your template sentences unambiguously define the polarity of the  object properties.    I was just thrown by the fact that I was expecting INT1 and INT2 to always map to the subject and object respectively - which, as it turns out, is not your convention.  I understand your convention now so my problem is solved.  
OpenCyc has some very clear temporal interval relation definitions that I've used over the years but you'd have to get permission.  But I should note that the w3c _time_ ontology always leads with INT1 as the subject of  the temporal relation -FWIW.

Best regards!

-Eric

**Comment by neilotte** [comment]
No problem Eric. And thanks for the tip regarding the w3c wording.  I'll remember this when we revisit the wording of our definitions in review.

**Comment by alanruttenberg** [comment]
These should cite and align with the [Allen interval algebra](https://en.wikipedia.org/wiki/Allen's_interval_algebra) also see the [Common Logic definitions for BFO ](https://github.com/BFO-ontology/BFO-2020/blob/25c834ed1c33997b756d5f62fc763e09f9826c0c/src/owl/profiles/temporal%20extensions/contributions/allen-relation-definitions.cl)

**Comment by alanruttenberg** [comment]
Yes that is what I am saying. I believe there's already an issue saying they should cite Allen as definition source #131.

**Comment by johnbeve** [comment]
Got it, I'll close this issue but cite it in https://github.com/CommonCoreOntology/CommonCoreOntologies/issues/131
Thanks!
