### ISSUE TITLE
Issues involving Waste Management Facility and its subclasses

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#295]
According to the former’s definition, a waste management facility manages waste _from its inception_ to its final disposal. However, few instances of its subclasses--Landfill and Sewage Treatment Facility--actually do this. Instead, the waste exists prior to being transferred to such facilities.

It might be possible to resolve this issue by changing the definition to something like:

> A Facility that is designed for managing waste at its final disposal and for some time prior to it.

However, I worry that even this isn’t quite right. Suppose a facility is designed for processing waste during the middle of its existence, after which it is transferred to another facility for final disposal. Given either the current definition or the revised one presented above, such a facility would not count as a waste management facility, which seems mistaken.

Perhaps, then, the correct definition is something like this?:

> A Facility that is designed for managing waste for some portion of the waste’s existence.

**Comment by swartik** [comment]
In the interest of making CCO definitions refer to CCO concepts, should a Waste Role be added to CCO? Although, because one person's waste is another person's treasure, I'm having difficulty formulating a definition.

**Comment by cameronmore** [comment]
Not sure personally, it really seems to get into the domain level for infrastructure or a similar area. This does raise the problem of portion of waste material, which is more narrow than food or human waste, it's more designed for waste that is the output of some act of artifact processing. Medical waste products are certainly waste, but are not outputs of Acts of Artifact Processing but rather Acts of Artifact Employment. The definition of portion of waste material does not cover cases where artifacts are used and them disposed, or designed for single use like medical artifacts.

Certainly I think that Portion of Waste Material should be changed, and maybe that definition could be used to inform a waste role term.

For reference:

`Portion of Waste Material = A Portion of Processed Material that serves no further use in terms of the initial user's own purposes of production, transformation, or consumption such that the Agent wants to dispose of it.`

`Portion of Processed Material = A Material Artifact that is the output of an Act of Artifact Processing.`
