### ISSUE TITLE
Rationale for ‘has process part’ definition?

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#297]
The definition reads:

> x has_process_part y iff x and y are instances of Process, such that y occurs during the temporal interval of x, and y either provides an input to x or receives an output of x, or both.

I find this definition somewhat obscure and difficult to evaluate, and I suspect it would be difficult to apply. Moreover, I find it puzzling, since it seems like 'has process part' could be defined more straightforwardly as follows:

> x has_process_part y iff x and y are instances of Process, such that x has occurrent part y.

So does anyone have a sense of what the rationale is for the current definition?

**Comment by cameronmore** [comment]
In the interest of consolidating, can we migrate this comment over to #145 ? @swartik has expressed concerns over this property there, and I think I would agree that your revised definition is the way this property is used in practice.

**Comment by gregfowlerphd** [comment]
@cameronmore: Good idea. Done.
