### ISSUE TITLE
Definition for Priority Scale in tension with label

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#299]
Is a priority scale a scale, as suggested by the label ‘Priority Scale’, or is it instead something that _describes_ a scale, as the relevant definition says?

If the latter, the current definition seems fine (though the label's kind of odd). However, if the former, perhaps the definition should be changed to something like the following?:

> A Reference System that consists of a scale used to rank or identify the importance of entities of the specified type.

**Comment by cameronmore** [comment]
Definitely agree.

An instance of reference scale may be the US Department of Homeland Security Advisory System, described here as:

> The Nation requires a Homeland Security Advisory System to provide a comprehensive and effective means to disseminate information regarding the risk of terrorist acts to Federal, State, and local authorities and to the American people. Such a system would provide warnings in the form of a set of graduated "Threat Conditions" that would increase as the risk of the threat increases. At each Threat Condition, Federal departments and agencies would implement a corresponding set of "Protective Measures" to further reduce vulnerability or increase response capability during a period of heightened alert. [Source](https://georgewbush-whitehouse.archives.gov/news/releases/2002/03/20020312-5.html#:~:text=Elevated%20%3D%20Yellow%3B,risk%20of%20a%20terrorist%20attack.)

So, 'Green' may be an instance of a Priority Measurement Information Content Entity, where that measurement uses the Department of Homeland Security Advisory System priority scale.

(besides the possibility that a threat scale may not exactly be a priority scale, same principle)

**Comment by neilotte** [comment]
An update has been merged into development to address this issue. Closing now. Thanks!
