### ISSUE TITLE
Typo in definition of cco:has_process_part

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#3]
The definition of cco:has_process_part is:

> For processes P1 and P2, P1 has process part P2 if and only if P2 occurs on a temporal interval that is during the temporal interval of P1 and P2 either provides an input to P1, recieves an output of p1 or both.

The last "p1" should be "P1".

**Comment by rorudn** [comment]
Will fix

**Comment by APCox** [comment]
Typo fixed.
