### ISSUE TITLE
Term Request

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#30]
There is a need for the classes 'Animal' and 'Plant' in my group. Could these be added to CCO?

**Comment by mark-jensen** [comment]
I think these would be good additions to CCO. Starting with Wikipedia, NCIT, and NCBITaxon...

CCO:Animal =def An organism that is multicellular, eukaryotic, heterotrophic, and capable of motility for part of its life.
subclassOf CCO:Organism

CCO:Plant =def An organism that is multicellular, eukaryotic, autotrophic, and has cells that contain  chloroplasts and walls made of cellulose.
subclassOf CCO:Organism

CCO:Organism = defined by the disjunction of its subclasses
subclassOf BFO:object

Move CCO:Person to subclass of CCO:Animal

**Comment by neilotte** [comment]
Sounds good Mark. For CCO:Organism, how about:

An object that is an instance of a type whose instances are routinely capable of bearing the biological quality of life. 

?

Or something like it. This would allow one to punt on the question of whether a dead organism is an organism, as well as provide some criteria (aside from a subclass restriction) for membership.

**Comment by neilotte** [comment]
Compare also wit the present treatment in Uberon. 

http://www.ontobee.org/ontology/UBERON?iri=http://purl.obolibrary.org/obo/UBERON_0000468

**Comment by mark-jensen** [comment]
@neilotte CCO updated to include requested terms. For now, I stuck with leaving `organism` a simple enumeration. I am sympathetic to the qualities of life approach, but then start to feel the slope get slippery. Dunno, maybe I need better shoes...

I appreciate the UBERON approach, in general think it works, but at this point I don't believe we would commit to adopting in CCO the full UBERON taxonomy and definitions. We definitely have room to improve our representation, as well as add metadata linking our classes to external ontologies.

**Comment by mark-jensen** [comment]
o

**Comment by mark-jensen** [comment]
@neilotte The added terms are available in the latest commit on the new `versions` branch. See #34. This is a first pass and subject to revision. For now, I stuck with a simple enumeration for `organism`. I am sympathetic to the qualities of life approach, but then start to feel the slope get slippery. Dunno, maybe I need better shoes...

I believe there is room for improvement: eg- adding terms for bacteria, maybe virus, and including a more friendly NL def for `organism`, and for sure we should add metadata linking these classes to external ones where it makes sense. Feedback always welcome.

I appreciate the UBERON approach, and think its works for the right applications, but I don't believe at this point CCO will commit to the UBERON taxonomy or their definitional strategy. 

Leaving this issue open for continued discussion.
