### ISSUE TITLE
Add term for decibels relative to isotropic (dBi)

### ISSUE THREAD

**Issue by Donna-Jones** [CommonCoreOntology/CommonCoreOntologies#306]
Decibels relative to isotropic (dBi) is a unit of measurement that describes how much power an antenna transmits in a single direction when compared to an isotropic radiator, which transmits in all directions at once. The difference between the two is called antenna gain, which is represented as a numerical value in dBi. The acronym dBi is also written out as decibels relative to isotrope, decibels relative to isotropic radiator, decibels over isotropic, decibels over isotropic antenna, decibels relative to an isotropic reference antenna and other variations.

**Motivation for adding term:**  While the CCO has an individual for Decibel Measurement Unit it does not include the term for the power measurement dBi. 

**Preferred term label:**  Decibel Isotropic Measurement Unit
 
**Synonyms:**  dBi
 
**Citation or source for definition:**  Sheldon, Robert. “Decibels Relative to Isotropic (dBi).” WhatIs. N.p., 23 Feb. 2023. Web. <https://www.techtarget.com/whatis/definition/decibels-relative-to-isotropic-radiator-dBi>.
 
**Parent term:**  Measurement Unit of Power

**Your contributor information:**  Donna Jones, donna.jones3@dodiis.mil

**Comment by CarterBeauBenson** [comment]
dc:contributer was used in the new pull request and dc was not placed in the prefix declaration. This is preventing the Units of Measure ontology from opening in protege
