### ISSUE TITLE
`cco:has_familial_relationship_to` should be symmetric

### ISSUE THREAD

**Issue by justin2004** [CommonCoreOntology/CommonCoreOntologies#309]
shouldn't `cco:has_familial_relationship_to` be symmetric? 

currently it is not:
<img width="842" alt="image" src="https://github.com/user-attachments/assets/6017f1d6-37d5-43b8-9e78-d3bcacdefd6d">

**Comment by mark-jensen** [comment]
That would require all of its subtypes to be symmetric as well, which isn't the case.

**Comment by justin2004** [comment]
That's not true. Symmetry doesn't propagate to subproperties. 

```
:justin :has_aunt :sally .
:justin :has_familial_relationship_to :sally .
:sally :has_familial_relationship_to :justin .
```

those are all things I might like to express.

**Comment by swartik** [comment]
@justin2004, I was pondering this and noticed the skos:scopeNote for cco:is_spouse_of:

> Given a stronger temporal interpretation, this property may be symmetric.
> For more info please refer to https://github.com/BFO-ontology/BFO-2020/tree/master/src/owl/temporal%20extensions.

Unfortunately, that link doesn't work. I poked around on the branches and found:

> https://github.com/BFO-ontology/BFO-2020/blob/release-2024-01-10/documentation/temporal%20extensions/temporalized%20relations/temporalized-relations.pdf

Anybody know if this is the correct document?

**Comment by caseythart** [comment]
> That would require all of its subtypes to be symmetric as well, which isn't the case.

This seems to suggest that if:

-. :Joe :hasFamilialRelationship :Sally
-. :hasSister rdfs:subPropertyOf :hasFamilialRelationship
-. :hasFamilialRelationship a owl:SymmetricProperty


Then also:

-. :Sally :hasSister :Joe

But that's just incorrect. To say that familial relation having is symmetric in general does not commit us to saying that every more specific familial relation is symmetric. For another example, we might have :near as a symmetric relation, even though :touchesOnTheLeft isn't, though clearly (:touchesOnTheLeft rdfs:subPropertyOf :near).

**Comment by mark-jensen** [comment]
@justin2004 Thanks for raising this issue as it required me to update my understanding of the OWL direct semantics. Property characteristics do not necessarily downward propagate. I think in all cases they must upward propagate. Need to confirm that.

However, as @swartik points out, in v1.5 of CCO with the adoption of BFO2020, we dropped asserting property characteristics for continuant properties as they may not all always hold given a particular temporal interpretation.

The correct link is: https://github.com/BFO-ontology/BFO-2020/tree/master/src/owl/profiles/temporal%20extensions

**Comment by caseythart** [comment]
@mark-jensen : The issue of temporal interpretation seems orthogonal here. If Joe has a familial relationship with Sally over any time interval, then Sally will have a familial relationship with Joe over that same interval. Temporal stuff is indeed complicated, but that's irrelevant here, unless I'm missing something.

**Comment by justin2004** [comment]
> we dropped asserting property characteristics for continuant properties as they may not all always hold given a particular temporal interpretation.

if you followed that rule you'd have to make these not symmetric (they currently are):
```
cco:is_first_cousin_of 
cco:is_half_sibling_of
cco:is_second_cousin_of
cco:is_sibling_of
etc.
```

**Comment by neilotte** [comment]
An update has been merged into develop reflecting this issue. Closing.

**Comment by caseythart** [comment]
@neilotte : Could you link to the update? I'm curious what the resolution is.

**Comment by neilotte** [comment]
@caseythart No problem. For any of these, if you select 'Pull Requests' and then click the 'closed' link to filter on closed PRs, you should be able to find them. In this case, please see: https://github.com/CommonCoreOntology/CommonCoreOntologies/pull/315
