### ISSUE TITLE
Provide tags in GitHub repo for versions

### ISSUE THREAD

**Issue by timrdf** [CommonCoreOntology/CommonCoreOntologies#31]
https://github.com/CommonCoreOntology/CommonCoreOntologies/commit/0838e2dda02777c176f9f4425335c71ab388b0c3 reflects a change from "Version 1.0.1" to "Version 1.1", but the [main page's](https://github.com/CommonCoreOntology/CommonCoreOntologies) "branch > tags" has "Nothing to show".

Could you please add tags to the git repo to reflect the release points for these versions?

Thanks.

**Comment by mark-jensen** [comment]
Thanks for the reminder @timrdf. Will do.

**Comment by mark-jensen** [comment]
Tags added for both versions.
