### ISSUE TITLE
Definition of ‘Spherical’ too broad

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#312]
The definition reads:

> A Three Dimensional Shape inhering in a bearer in virtue of it having round cross sections.

This mistakenly suggests that cylinders are spherical, given that they too have round cross sections. Maybe add ‘only’ before ‘round’?

**Comment by cameronmore** [comment]
I think 'only' is a good addition. If a spherical object is attached to a cube, we would not say that the entire thing bears a spherical quality, but only part of it bears that quality.

**Comment by gregfowlerphd** [comment]
@cameronmore: Having thought about it more "...in virtue of all of its cross sections being round" might be better, because more explicit.
