### ISSUE TITLE
Request for term "Representation"

### ISSUE THREAD

**Issue by arsarkar** [CommonCoreOntology/CommonCoreOntologies#32]
I want to request the term “Representation” to be included in CCO based on the necessity and suitability of this term in modeling Specification (mainly design specifications). Apology for making this note a little extensive, but it was required to corroborate some points.  

A product design is a set of specifications, e.g. functional (teleology), component and assembly (mereonomy and weak/strong connection), material (constituents), geometry, dimension and tolerance (structural). Specifications are not Quality because Quality instances only inhere_in an independent continuant but such artifact (a particular product) (Material_Entity) may not necessarily exist during design phase.

We can use Information Content Entity (ICE) to define specifications; however, ICEs need to generically depend (g.depend) on a material entity (def.). As the physical product does not exist at the design phase, what material entity should the ICE g.depend on? 

(A related question: is “g.depending on a material entity” a necessary condition for ICE?)
In a possible model, these specification ICEs may g.depend on an Information Bearing Artifact (IBA), which may suitably denote the product design document (CAD file).

Precisely, a product design is a collection of various specifications (mental qualities) of a “conceptual product”, still lacking embodiment. Moreover, these specifications need to conform to the actual Qualities of the product (particular), which is manufactured following the design (universal).

In the article “Aboutness: Towards foundations for the information artifact ontology,” by B. Smith and W. Ceusters, “Representation” is defined as “a QUALITY which is_about or is intended to be about a PORTION OF REALITY(POR).” This notion is extremely suitable for representing specifications as explained: “Note that ‘representation’ is thus more comprehensive in scope than ‘ICE,’ even on our proposed more inclusive definition of the latter, since an ICE must in every case be about some portion of reality, where the aboutness in question must always be veridical, so that ‘being about’ is a success verb. A representation, in contrast, is required merely to intend to be about something, and this intention might fail.” (Smith, 2012)

Representation can be treated as quality universal, which concretizes the specification ICEs, acting as universals expressing various product specifications. 
**Representation** = **Information_Quality_Entity** and _inheres_in_ some **Information_Bearing_Artifact** and _is_represented_by_ some **Information_Content_Entity**  

In fact, the qualities inhering_in a product instance should conform to corresponding design specifications, which was inhering_in IBA at the design phase. These conformance criteria may be expressed as, 
**x** _is_conformant_to_ **y** = **x** is a **Quality** or **Artifact** and **y** is a **Representation** and there exists some **ICE** **g** such that **g** _is_about_ **x** and **y** _concretizes_ **g**.

**Comment by cameronmore** [comment]
With the publication of the cognitive process ontology, as well as design patterns regarding digital twins, this issue has been addressed.
[Cognitive Process Ontology repository](https://github.com/CommonCoreOntology/CognitiveProcessOntology), [CPO paper](https://philarchive.org/archive/LIMOAC)
