### ISSUE TITLE
Representational ICE definition tweak

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#33]
Presently, Representational ICE is defined: 

A Descriptive Information Content Entity that consists of a set of propositions or an image that represents some Entity.

However, CCO also defines 'image' as an information bearing entity. Hence, the definition is misleading. 

Perhaps a different label for the present class 'image' is all that is needed. Something like 'Concretized Image' or 'Image inhering in a Bearer'.

**Comment by APCox** [comment]
Edited the definition of 'Representational ICE' in version 1.3 to clarify that it is the content of an image (which is an IBA) that does the representing. Also updated related examples of usage to make similar clarifications.
