### ISSUE TITLE
Resolving annotation label URLs

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#35]
The URLs I've tried for the "has axiom label" annotations (e.g., http://purl.obolibrary.org/obo/bfo/axiom/134-001) yield a 404 error. I assume this means the URLs are notional. Are there plans to make them resolve? Is there currently an online table listing all the BFO axioms?

**Comment by rorudn** [comment]
This one should be directed to the BFO group. I checked the latest version of BFO at their GitHub site and none of a small sample of the URLs resolved.

**Comment by swartik** [comment]
Thanks – I'll report it there.
