### ISSUE TITLE
The NL definition of 'realizes' is incorrect. 

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#37]
Hey all,

The NL definition for 'realizes' restricts the range to 'Function' and also is derived from http://www.berkeleybop.org/ontologies/obo-all/ro_proposed/ro_proposed.owl, and this link appears to be broken. 

Please revise to RO def and source. 

http://www.ontobee.org/ontology/RO?iri=http://purl.obolibrary.org/obo/BFO_0000055

**Comment by mark-jensen** [comment]
@neilotte Thanks for pointing this out. We can modify the NL def for now, but that's just a superficial glitch. The D/R axioms are correct. The real fix is forthcoming with the update of CCO to use RO Core. See #23.

**Comment by mark-jensen** [comment]
Fixed with update to latest RO 3f15ec4
