### ISSUE TITLE
Format Request

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#38]
Just a note that it would be convenient (since you're saving local files anyway) to have the BFO artifacts here in Turtle rather than in OWL. Although this doesn't matter for those working in Protege, TopBraid won't open files with an owl extension.

**Comment by mark-jensen** [comment]
@neilotte Changing the extension from .owl to .rdf allows files encoded in RDF/XML to load normally in applications like TopBraid. 

However, thinking about this raised a question about how CCO currently imports RO. Potentially our current method isn't as extensible for some users as it could be. Going forward, CCO will import subset of RO that is extracted into a import module built automatically during the release process. To maintain consistency with the rest of CCO, and be usable in a wider array of software applications, both the RO module and BFO will be encoded in turtle during that process.

As an aside, if you need an ontology encoded in an alternate syntax, opening it in Protege and then "saving as" allows for selecting from several alternatives. Use of Robot [convert ](http://robot.obolibrary.org/convert)  is easier though.

**Comment by neilotte** [comment]
Thanks Mark. I follow the extension vs. serialization issue. Didn't mean to imply otherwise. 

Just a thought: this seems like the sort of thing that's above CUBRC's purview, and that should really be coming from the overseers of the BFO artifacts. Perhaps this hasn't been an issue in the past, with most of the OBO community using Protege and a number of python/lisp libraries and scripts. But with more TopBraid users coming online, it seems they should be providing a product tailored by their needs as well.

**Comment by mark-jensen** [comment]
I see that many Foundry ontologies provide alternate serializations, obo format, json, etc. I guess if enough users, or a VIP, makes the request, those developers would consider producing alternate formats as part of a release. I agree that it's beyond the scope of CCO to address such issues.

Ok to close this?
