### ISSUE TITLE
The relationship between ISEs and ICEs

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#42]
The class 'Information Structure Entity' is defined as: "A Generically Dependent Continuant that is not an Information Content Entity (ICE) but which is complemented or complementable by some ICE to create another ICE." 

There is, however no object property such as 'complements' in CCO, and the relationship between, say, a cell in a spreadsheet and the information in any copy of a spreadsheet file. This is also not discussed in the 'Model Language with CCO' doc, but seems highly relevant. This leaves it unclear how to represent the relationship between instances of ISE and instances of ICE. Note: I am particularly concerned with software files, which I understand the CCO treats as IBEs.

**Comment by rorudn** [comment]
Information Structure Entity has been obsoleted in version 1.3
