### ISSUE TITLE
Problem with 'enemy'

### ISSUE THREAD

**Issue by avsculley** [CommonCoreOntology/CommonCoreOntologies#431]
'Enemy' is axiomatized as a person but it seems true that non-person agents can be enemies. At least, this is what the definition of 'enemy role' says. 

The options are similar to the options in #422 : we can either 

1) change the label to 'Enemy Person' and add a term for enemy group/just leave it to users to create enemy groups themselves if needed. Or

2) deprecate 'enemy' IRI and create a new IRI that allows for all kinds agents to bear some enemy role.

In this case, I lean toward option 1 as it conforms more to established design pattern of 'Allied person'

**Comment by cameronmore** [comment]
changing the label to 'enemy person' seems the right call, but I'm not sure we should add other equivalences like "Enemy Organization"

**Comment by neilotte** [comment]
@cameronmore I recommend changing the label as you have indicated above and closing this issue, but creating a separate issue to address a more comprehensive review of this and other recent classes that @avsculley has identified recently (e.g. Allied Person, Organization Member) to ensure these issues are being addressed consistently and then labeling this review ticket for the 2.0 release. 

@mark-jensen @johnbeve FYSA.
