### ISSUE TITLE
Protege 5.5 can't parse latest version on develop branch

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#432]
The recent change to the range of `has_text_value` that adds rdf:langString causes Protege 5.5 to fail when parsing InformationEntityOntology.ttl. Because not everyone has switched to 5.6, I recommend modifying README.md. Replace the sentence:

> Developers may clone this repository and directly import AllCoreOntology.ttl in an ontology editor such as [Protégé](https://protege.stanford.edu/) to generate the merged version of the eleven CCO ontologies.

with:

> Developers may clone this repository and directly import AllCoreOntology.ttl in an ontology editor such as [Protégé](https://protege.stanford.edu/) 5.6 (or later) to generate the merged version of the eleven CCO ontologies.

**Comment by cameronmore** [comment]
When I tested the solution of modifying the range, I only used 5.6, but I'm inclined to just drop the range altogether now. Thoughts @neilotte @johnbeve @mark-jensen ?

**Comment by mark-jensen** [comment]
This touches on a difficult to identify boundary between the representational space of ontologies and the lexical one that our data lives in. I am skeptical that a mid-level ontology is the appropriate place to enforce that boundary. It seems to me that the particulars of more highly restricted data properties should be left to domain extensions and application-specific ontologies. I know @alanruttenberg has some thoughts on this, which are compelling to me. 

A broader discussion is required. 

In the short run, if the more restrictive range is causing problems, then I say drop the range all-together for the time being.
