### ISSUE TITLE
Equivalence Classes for Agents

### ISSUE THREAD

**Issue by cameronmore** [CommonCoreOntology/CommonCoreOntologies#435]
To be addressed in release 2.0 is the issue of axioms for classes such as Enemy Organization (per issue #431 ) , Organization Member (per #422 ), and existing terms such as Allied Person and Neutral Person. The question is, since the associated roles can be born by any agent (person or organization), do we need equivalence classes for all the persons and agents for the different roles.

@avsculley @mark-jensen @johnbeve @neilotte

**Comment by alanruttenberg** [comment]
Sounds like a discussion ;-)

**Comment by cameronmore** [comment]
To address this issue, we could either:

1. Deprecate the equivalence classes.
2. Add more equivalence classes to reflect the allied persons / enemy person / neutral person in the organization hierarchy.
3. Leave the classes as is but note that no new equivalence classes along these lines should be created.

I would prefer either 1 or 3 over 2, and deciding between 1 and 3 may depend on how many CCO users depend on those IRIs. I prefer 1 over 2 because I do not see a clear rationale for adding more equivalence classes that seem to be shortcuts for semantics that can be built out of the already-existing CCO elements, and do not see clear guidance for when to create or not creating them (at the mid-level of CCO).

@alanruttenberg @mark-jensen @neilotte thoughts?

**Comment by neilotte** [comment]
@cameronmore I lean toward 2 because useful, but interested in further conversation here. I'm marking this for 2.1 to allow 1.7 and 2.0 to be more straightforward. Recommend we can discuss this in the next two weeks and reach consensus quickly.

**Comment by mark-jensen** [comment]
I agree with @neilotte that this should be pushed to CCO v2.1 as it touches on a broader discussion.
