### ISSUE TITLE
Query min_1_ontology_title.sparql uses wrong annotation property?

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#438]
I was looking at the SPARQL queries used for quality control and noticed that [min_1_ontology_title.sparql](../tree/develop/.github/deployment/sparql/min_1_ontology_title.sparql) has in its header comment:

> Any owl:Ontology must have a dcterms:title annotation property.

But the query filters on `rdfs:label`, not `dcterms:title`.

**Comment by johnbeve** [comment]
Thank you @swartik; will fix, see PR https://github.com/CommonCoreOntology/CommonCoreOntologies/pull/441
