### ISSUE TITLE
NautralLanguage still present

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#448]
In commit [30e9a4e](https://github.com/CommonCoreOntology/CommonCoreOntologies/commit/30e9a4e8980122f3ffe4edec203058af792ad122) (head of develop branch), class ArtificialLanguage declares itself disjoint with NautralLanguage, not NaturalLanguage.

**Comment by swartik** [comment]
The query:

```
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?cls
WHERE {
  ?cls a owl:Class
  FILTER isIRI(?cls)
  FILTER NOT EXISTS { ?cls rdfs:subClassOf ?supercls }
}
```
would be useful in the .github/deployment/sparql directory. It shouldn't return anything other than class entity.

**Comment by neilotte** [comment]
This was addressed in PR 450.
