### ISSUE TITLE
Typo in definition of "has process part"

### ISSUE THREAD

**Issue by Mttbnchtt** [CommonCoreOntology/CommonCoreOntologies#45]
The definition of _has process part_ is "For processes P1 and P2, P1 has process part P2 if and only if P2 occurs on a temporal interval that is during the temporal interval of P1 and P2 either provides an input to P1, recieves an output of P1 or both." Correction: recieves --> receives.

**Comment by mark-jensen** [comment]
@Mttbnchtt Thanks! Will fix.

**Comment by mark-jensen** [comment]
closed with dd18eb09e9dcf0258b0780cdc8a284491e78dc79
