### ISSUE TITLE
Add ‘exactly’ to ‘Triangular’ definition for precision’s sake?

### ISSUE THREAD

**Issue by gregfowlerphd** [CommonCoreOntology/CommonCoreOntologies#461]
The current definition indicates that anything that has three angles and three sides is triangular. However, one might argue that a square has three angles and three sides--it simply has one more of each besides! For the sake of precision, I’d argue that ‘exactly’ should be added before each instance of ‘three’.

**Comment by neilotte** [comment]
@gregfowlerphd Makes sense to me. Wanna open a PR?
