### ISSUE TITLE
Several modules are missing dcterms: prefix declarations

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#471]
The following modules use the dcterms: prefix:

> AgentOntology.ttl
> ArtifactOntology.ttl
> CurrencyUnitOntology.ttl
> EventOntology.ttl
> ExtendedRelationOntology.ttl
> FacilityOntology.ttl
> GeospatialOntology.ttl
> InformationEntityOntology.ttl
> QualityOntology.ttl
> TimeOntology.ttl
> UnitsOfMeasureOntology.ttl

Of these, only four declare the prefix:

> AgentOntology.ttl
> ExtendedRelationOntology.ttl
> GeospatialOntology.ttl
> QualityOntology.ttl

(I know others are currently working on adding license annotations, so apologies if I'm catching the modules in the middle of a change sequence.)

**Comment by mark-jensen** [comment]
@swartik Thanks for catching that. Surprised that passed our QC checks; undeclared prefixes are a no-no.

**Comment by johnbeve** [comment]
https://github.com/CommonCoreOntology/CommonCoreOntologies/pull/477 opened to address, thank you @swartik!
