### ISSUE TITLE
Name of SPARQL file for BFO superclass constraint needs a suffix

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#478]
Just an "ı" that needs dotting. The newly added SPARQL query to test whether all CCO classes have a BFO superclass is in a file named:

> all-CCO-classes-have-a-BFO-superclass

It should be named:

> all-CCO-classes-have-a-BFO-superclass.sparql

**Comment by johnbeve** [comment]
Thanks @swartik. To be fixed here https://github.com/CommonCoreOntology/CommonCoreOntologies/pull/483
