### ISSUE TITLE
UnitsOfMeasureOntology.ttldoes not parse with owlapi

### ISSUE THREAD

**Issue by cmungall** [CommonCoreOntology/CommonCoreOntologies#48]
```
$ robot merge -i AllCoreOntology.ttl -o merged.owl 
[Fatal Error] :1:120: The reference to entity "lthttp:" must end with the ';' delimiter.
Could not load imported ontology: <http://www.ontologyrepository.com/CommonCoreOntologies/Mid/UnitsOfMeasureOntology> Cause: Problem parsing http://www.ontologyrepository.com/CommonCoreOntologies/Mid/UnitsOfMeasureOntology
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser@61c9c3fd
```

**Comment by cmungall** [comment]
The problem is with http://www.ontologyrepository.com/CommonCoreOntologies/Mid/ExtendedRelationOntology

The version in the repo is OK

However, when the URL is fetched over the web it is returned as an HTML document:

```
<html><div class="container"><pre><meta http-equiv="content-type" content="text/html; charset=UTF-8">@prefix : &lthttp://www.ontologyrepository.com/CommonCoreOntologies/Mid/ExtendedRelationOntology/&gt .
@prefix cco: &lthttp://www.ontologyrepository.com/CommonCoreOntologies/&gt .
@prefix obo: &lthttp://purl.obolibrary.org/obo/&gt .
@prefix owl: &lthttp://www.w3.org/2002/07/owl#&gt .
@prefix rdf: &lthttp://www.w3.org/1999/02/22-rdf-syntax-ns#&gt .
@prefix xml: &lthttp://www.w3.org/XML/1998/namespace&gt .
@prefix xsd: &lthttp://www.w3.org/2001/XMLSchema#&gt .
@prefix rdfs: &lthttp://www.w3.org/2000/01/rdf-schema#&gt .
@base &lthttp://www.ontologyrepository.com/CommonCoreOntologies/Mid/ExtendedRelationOntology&gt .
...
```

**Comment by timrdf** [comment]
The URL does not content negotiate for either Turtle or RDF/XML

```
bash-3.2$ curl -s -H "Accept: text/turtle" -L http://www.ontologyrepository.com/CommonCoreOntologies/Mid/ExtendedRelationOntology | head -1
<html><div class="container"><pre><meta http-equiv="content-type" content="text/html; charset=UTF-8">@prefix : &lthttp://www.ontologyrepository.com/CommonCoreOntologies/Mid/ExtendedRelationOntology/&gt .
```

```
bash-3.2$ curl -s -H "Accept: application/rdf+xml" -L http://www.ontologyrepository.com/CommonCoreOntologies/Mid/ExtendedRelationOntology | head -1
<html><div class="container"><pre><meta http-equiv="content-type" content="text/html; charset=UTF-8">@prefix : &lthttp://www.ontologyrepository.com/CommonCoreOntologies/Mid/ExtendedRelationOntology/&gt .
```

**Comment by mark-jensen** [comment]
Thanks for pointing this out! We just set up our servers to resolve IRIs and need to still need to work out the formatting for ontologies vs individual terms.

**Comment by mark-jensen** [comment]
@cmungall @timrdf What is the standard return that a tool like Robot or Protege needs to consume an ontology file? Do they always specify a format in an Accept header? The OBO principle states:

>  However, the official owl PURL for the ontology must resolve to a syntactically valid OWL file in an RDF in RDF-XML syntax.

Does that mean for integration with OBO ontologies and their dev pipelines, our URLs should return RDF/XML as a defualt?

**Comment by cmungall** [comment]
ttl is fine for cco but I think this is orthogonal. I would not make any
assumptions about accept headers

**Comment by timrdf** [comment]
If a client makes a request with a reasonable Accept header, then it's proper to oblige. If an Accept header is not provided by a naive client, the server can choose to default to the oldest legacy serialization (application/rdf+xml) to maximize compatibility.

This distinction is more important when requests of the resource are made by either humans (text/html) or machines (text/turtle).

**Comment by cmungall** [comment]
What if the file already has a format implicit in the suffix? What should
happen if I request html from a url that ends with .ttl? People doing fancy
things with conneg can be a source of complexity and bugs. Fine for pages
about terms etc. But for Duke file serving keep it simple imho

**Comment by mark-jensen** [comment]
Both full ontology and individual term IRIs are returning requests. They can be loaded via IRI into tools like Protege or Robot.
