### ISSUE TITLE
Issues concerning has-some-member-of-located-in and has-all-members-of-located-in

### ISSUE THREAD

**Issue by michaelrabenberg** [CommonCoreOntology/CommonCoreOntologies#492]
1. has-some-member-of-located-in has no domain or range restriction, but its sub-property has-all-members-of-located-in does (Object Aggregate and Material Entity, respectively). I assume these object properties should have the same D/R restrictions.

2. Unadorned located-in doesn’t have range Material Entity; rather, it has the more expansive range Independent Continuant and not Spatial Region. Is there a reason why has-all-members-of-located-in has a narrower range restriction than located-in? 

3. The definitions of has-some-... and has-all-... both reflect the assumption that their ranges are Material Entity. If it'd make sense to give has-some-... and has-all-... each a range of Independent Continuant and not Spatial Region, then it'd make sense to revise these definitions accordingly.

4. I think dropping the “of” from these object properties’ labels would increase readability. As phrased, they sound like labels for three-place predicates. Alternatively, the "of" could be replaced by "part," so you'd get "has-some-member-part-located-in," and similarly for the has-all-... object property.

5. Given that the only subproperty of has-some-member-of-located-in is has-all-members-of-located-in, I assume this (from the 1.6 summary) is miswritten: “cco:has_member_of_located_in now a subproperty of cco:has_some_member_of_located_in” (https://github.com/CommonCoreOntology/CommonCoreOntologies/releases/tag/v1.6-2024-09-26). I assume it should instead be "cco:has_all_members_of_located_in now a subproperty of cco:has_some_member_of_located_in."

**Comment by mark-jensen** [comment]
@michaelrabenberg I agree we need to tighten this up. The domain for these two properties should be `object aggregate`. I can see no reason not to have the range the same as BFO `located in`. @johnbeve @neilotte @APCox Agree?

Removing 'of' from the labels and improving defs is fine by me. 

re point 6: note that the local ID for the property labeled "has all members of located in" is `has_member_of_located_in`

**Comment by mark-jensen** [comment]
see #513
