### ISSUE TITLE
Definitions didn't get changed in commit fe316dc

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#5]
The commit on Nov. 5 changed the class hierarchy. The corresponding cco:definition assertions didn't get updated. For example, cco:Birth was changed from a subclass of ProcessBeginning to a subclass of NaturalProcess, but the definition of cco:Birth still reads as follows:

    A Process Beginning that is a temporal part of a Biographical Life.

The version 1.0.1 distributed in August _does_ include an updated definition:

    A Natural Process of bringing forth offspring.

**Comment by APCox** [comment]
Birth is a subclass of NaturalProcess and is defined as:

> A Natural Process of bringing forth offspring.

**Comment by swartik** [comment]
I just pulled the repository and the definition for Birth is still the one that was assigned a bug label, not the one in APCox's 5/25 comment. GitHub says EventOntology hasn't been changed in 7 months. How do I access the corrected version?

**Comment by mark-jensen** [comment]
Apologies for that. We haven’t pushed our local changes to the public repo yet. I’ll follow up here with a solution ASAP.
