### ISSUE TITLE
Act of Condoling [sic]

### ISSUE THREAD

**Issue by michaelrabenberg** [CommonCoreOntology/CommonCoreOntologies#518]
"Act of Condoling" should be "Act of Consoling." The error appears in the rdfs:label and in the IRI.

**Comment by cameronmore** [comment]
Although similar, condoling and consoling are different (at least in some dictionaries). Consoling is often defined as giving moral strength or courage to, while condoling is more often the giving of sympathy, but the line is not clear.
Merriam Webster defines console (verb) as "to alleviate the grief, sense of loss, or trouble of" and condole as "to express sympathetic sorrow".

**Comment by michaelrabenberg** [comment]
Well I'll be! I won't be forgetting that word. Thanks for pointing that out.

So maybe a follow-up: Should Act of Condoling be in CCO but Act of Consoling *not* be in CCO?

**Comment by cameronmore** [comment]
I have no preference either way, though getting into the weeds of different acts of communication already seems like a domain-level task. If there is a desire from users, I see no reason not to add it as a sibling class--though it would raise the question of whether the acts are distinct enough (esp in common usage) to warrant two siblings.

I will close this issue, and if there is a desire, we can open another to add Act of Consoling.
