### ISSUE TITLE
Detected Material Entity Equiv Class Restriction

### ISSUE THREAD

**Issue by aellenhicks-jhuapl** [CommonCoreOntology/CommonCoreOntologies#56]
It seems to me that the equiv class restriction on DetectedMaterialEntity is too narrow. 

obo:BFO_0000040 (material entity) and (ro:participates_in some cco:DetectionEventSensorProcess)

For example, the material object that does the detecting also participates in this process, so would be classified as a Detected Material Entity as well. Likewise for an agentive operators of the detection artifact, etc.

Can this be relaxed to a subclass restriction?

**Comment by mark-jensen** [comment]
@aellenhicks-jhuapl Thanks for the catch. Will update asap.
