### ISSUE TITLE
Temporalizing Parthood Using Stasis

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#58]
I would like to say 'X has part Y **at T**' by saying 'X has_part Y and StasisOfParthood(w) and x and y participate_in w and w occurs on T. 

However, the present definition of stasis is more restrictive: 
"A Process in which some Independent Continuant endures and one or more of the dependent entities it bears does not change in kind or intensity." 

Can we weaken it so that it is something like the following: "A Process in which some Independent Continuant endures and either one or more of the dependent entities it bears does not change in kind or intensity, or it maintains some relation to another Independent Continuant."

**Comment by rorudn** [comment]
Seems reasonable but we want to preserve an easily understandable distinction between being in a state and participating in a process. It won't do to make it problematic for users to decide whether someone who is observing a sunset is participating in a stasis of observation or in an act of observation. I'd like to spend some time thinking about your suggested definition to see if there's a change that would mitigate this concern but i think we can make the change appear in the next version of the CCO.

**Comment by rorudn** [comment]
The definition of "Stasis" has been updated to: A Process in which one or more Independent Continuants endure in an unchanging condition.  This kind of opens the flood gates a bit on what the original scope of the extension of "Stasis" but we'll give it a try.

**Comment by swartik** [comment]
Is it then true that for every stasis there exists some condition,  associated in a way I cannot investigate as long as I'm reading this email on my phone?

Sent by Email+ managed by MobileIron

-------- Original Message --------

**Comment by mark-jensen** [comment]
Addressed with d4ea051

@neilotte is this satisfactory?

**Comment by neilotte** [comment]
@rorudn and @mark-jensen  -- Sorry for the slow reply. Yes, this is helpful. Thanks!
