### ISSUE TITLE
Different names for Process <-> Process Profile relationships

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#6]
In Section 4.9 of _Modeling Information with the Common Core Ontologies 1.0_, the figure shows individuals `act of motion 1` and `speed 1` linked by a property named `has profile`. In Section 3.2 of _An Overview of the Common Core Ontologies 1.0_ and in the Extended Relation Ontology, the property is named `has_process_part`.

**Comment by mark-jensen** [comment]
@swartik We use `has_process_part` to link a `process` to a `process profile`. 
The use of `has_profile` in the Modeling document is an error. Thanks!
