### ISSUE TITLE
Please remove 'rdfs:Literal' declarations

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#60]
I ran a search and there are six declarations that some value is an 'rdfs:Literal'. I would like to confirm with you that this is a bug, and request that these declarations be removed. 

Example1: 
 cco:ActOfCargoTransportation rdfs:label "Act of Cargo Transportation"^^rdfs:Literal

Example2: 
cco:MeasurementUnitOfGeocoordinate   cco:definition "A Measurement Unit specifying the geospatial coordinates of a location."^^rdfs:Literal

**Comment by mark-jensen** [comment]
That's a bug. Will fix asap.

**Comment by mark-jensen** [comment]
Fixed with d4ea051
