### ISSUE TITLE
Indicate on Readme.md which CCO-using Ontologies won't have Public URLs

### ISSUE THREAD

**Issue by lonniev** [CommonCoreOntology/CommonCoreOntologies#63]
The Readme.md has an attractive list of domain-specific CCO-using ontologies. However, all but the Emotion ontology do not offer a URL. Further, a Google search for the ontologies by name and visits to ontology repositories yield disappointing misses.

If these cited CCO-using ontologies are never going to be public (because of the sensitivity of their concepts?) then can they be moved to a sub-heading of the Readme.md like "Known Usages but Private to their Creators"?

**Comment by rorudn** [comment]
Yes, will do.

**Comment by mark-jensen** [comment]
Addressed with d4ea051. 

@lonniev Is this satisfactory?
