### ISSUE TITLE
What does it mean for an Act to be "at time t"?

### ISSUE THREAD

**Issue by eliasweatherfield** [CommonCoreOntology/CommonCoreOntologies#67]
The definitions for requires, prohibits and permits speak of independent continuants and an Act "at time t". I take t to be a temporal instant. Is t the starting instant of the Act or is it inside its temporal interval?

**Comment by rorudn** [comment]
The time referred to in these definitions is the temporal interval during which the acts occur.

**Comment by eliasweatherfield** [comment]
Thanks.
