### ISSUE TITLE
Object Properties Lacking Definitions

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#69]
Are there plans to add definitions for the object properties below? The non-familial relationships are the most pressing for our purposes. 

- aggregate has capability
- capability of
- capability of aggregate
- has affiliate
- has aunt
- has brother
- has brother in law
- has capability
- has daughter
- has daughter in law
- has father
- has father in law
- has granddaughter
- has grandfather
- has grandmother
- has grandson
- has half brother
- has half sister
- has husband
- has maternal aunt
- has maternal first cousin
- has maternal grandfather
- has maternal grandmother
- has maternal uncle
- has mother
- has mother in law
- has nephew
- has niece
- has organizational context
- has parent
- has paternal aunt
- has paternal first cousin
- has paternal grandfather
- has paternal grandmother
- has paternal uncle
- has sister
- has sister in law
- has son
- has son in law
- has step brother
- has step sister
- has uncle
- has wife
- instant is after
- instant is before
- is ancestor of
- is aunt of
- is brother of
- is brother-in-law of
- is child of
- is daughter in-law of
- is daughter of
- is descendent of
- is father in-law of
- is father of
- is first cousin of
- is geospatial coordinate reference system of
- is grandchild of
- is granddaughter of
- is grandfather of
- is grandmother of
- is grandparent of
- is grandson of
- is half sister of
- is half-brother of
- is half-sibling of
- is husband of
- is in-law of
- is maternal aunt of
- is maternal grandfather of
- is maternal grandmother of
- is maternal uncle of
- is measurement unit of
- is mother in-law of
- is mother of
- is nephew of
- is niece of
- is parent of
- is paternal aunt of
- is paternal grandfather of
- is paternal grandmother of
- is paternal uncle of
- is permitted by
- is prohibited by
- is reference system of
- is required by
- is second cousin of
- is sibling of
- is sister of
- is sister-in-law of
- is son in-law of
- is son of
- is spouse of
- is step-brother of
- is step-sibling of
- is step-sister of
- is subordinate role to
- is third cousin of
- is uncle of
- is used by
- is wife of
- language used in
- set described by
- set described by expected element
- set described by ordinality
- set described by proportion
- time zone identifier used by
- uses
- uses geospatial coordinate reference system
- uses language
- uses measurement unit
- uses reference system

**Comment by mark-jensen** [comment]
All properties and their inverses now have definitions. Except for the 50 or so familial properties. These, we believe, are self explanatory.

**Comment by mark-jensen** [comment]
Addressed in 44c635e
