### ISSUE TITLE
portion of processed material

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#7]
Since the class 'portion of processed material' also includes fluids and gases, this class appears to belong under material entity rather than object. Also, 'portion of material' should be the parent of 'portion of processed material', but presently the reverse is true, with every 'portion of material' being an instance of a 'portion of processed material'. 

Also:

1. The class lacks a definition.
2. Not all of its children seem to necessarily be processed (e.g. portion of food, portion of waste material)
3. 'Article of Solid Waste' is introduced as a subclass of portion of waste, but it isn't clear what the difference is between a portion and an article. 
4. Like the present treatment of 'portion of coolant', 'Portion of Waste' seems like a defined class consisting of a portion of material that bears a waste role, rather than an asserted class. The worry is that the assertion of the class can not account for the fact that the same portion can be waste in the context of one process, but a raw material to be used in a secondary process. The same seems true for portion of food and portion of fuel.

**Comment by rorudn** [comment]
Portion of Processed Material does include fluids and gases but stored in ways in which they can be transported and sold (as opposed to a free-floating cloud of gas in the atmosphere) hence on our reading these articles pass the test of being a BFO object (maximally causally unified material entity). 

The portion of processed material class was not defined but now that it is the subtype of portion of material should stand. It contains classes of processed raw material. 

Regarding the numbered items
1. Portion of Processed Material is now defined as an artifact that is the output of some act of artifact processing
2.  We're in the realm of artifacts here so instances of portion of food or portion of waste material should be limited to those that are the output of some act of artifact processing. This would include a stack of peaches for sale at a market or a pile of wood chips on the factory floor.  
3. An Article of Solid Waste is defined as being a portion of waste material having low liquid content. So the definition should make clear that we're using article and portion as close synonyms. Doesn't seem like a big enough issue to warrant a class name change.
4. Fair point. In version 1.3 we've begun the use of roles to classify artifacts by use. Did not get to waste, food or fuel. But will do so in future releases.
