### ISSUE TITLE
Please clarify 'designates' 

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#70]
The definition for 'designates' holds: 
"For all types T1 and T2, if T1 designates T2, then there is some instance of T1, t1, by which some instance of T2, t2,  is called, or classified, distinguished from others."

I'm not sure what this means. What are the 'types' here and why does 'designates' hold between both types and instances? Also, the relation is functional, but no mention of this is called out in the definition.

**Comment by mark-jensen** [comment]
We have updated the format for property definitions to make it clear the relations hold between instances of the specified types.

**Comment by mark-jensen** [comment]
Addressed in 44c635e
