### ISSUE TITLE
Definition of speed

### ISSUE THREAD

**Issue by aellenhicks-jhuapl** [CommonCoreOntology/CommonCoreOntologies#71]
The definition of Speed is "A Process Profile that is characterized by the rate of an object's change in position during some time period." However, this characterizes velocity, which is a distinct from speed.

**Comment by mark-jensen** [comment]
@aellenhicks-jhuapl  Thanks for pointing this out. Use of 'position' does seem to imply displacement rather than distance. 

Propose we change to "A Process Profile that is characterized by the rate of change in distance a Material Entity travels during some time period"

**Comment by mark-jensen** [comment]
Addressed in 44c635e

**Comment by APCox** [comment]
The definition of 'Speed' was modified in version 1.3 and the definition source for both it and 'Velocity' were changed.
