### ISSUE TITLE
'externally connects with' should be subproperty of 'connections with'

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#72]
It looks like 'externally connects with' should be a subproperty of 'connected with'.

- 'connected with' def =An immaterial entity im1 is connected with some immaterial entity im2 iff there exists some immaterial entity im3 that is common to both im1 and im2.

- 'externally connects with' def =An immaterial entity im1 externally connects with some immaterial entity im2 iff im1 connects with im2 and im1 does not overlap with im2.

**Comment by rorudn** [comment]
This an other edits to the RCC8 relationships have been made in version 1.3. See change file for details.
