### ISSUE TITLE
'bearer of' still be used incorrectly in descriptions of some properties. 

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#76]
When I run a text search for 'bearer of' over InformationEntityOntology.ttl (at https://raw.githubusercontent.com/CommonCoreOntology/CommonCoreOntologies/master/InformationEntityOntology.ttl), I get eight matches that appear to be out of date, and which should be replaced by 'is carrier of'. 

I haven't repeated this search for other files.

**Comment by mark-jensen** [comment]
Addressed in 44c635e
