### ISSUE TITLE
'has process part' should be subproperty of 'has part'

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#78]
I believe:  
http://www.ontologyrepository.com/CommonCoreOntologies/has_process_part
should be subproperty of
http://purl.obolibrary.org/obo/BFO_0000051

And also for their inverses.

**Comment by mark-jensen** [comment]
@neilotte While I agree that logically this is the case, I am skeptical of the need for this property. I am tempted to advocate that we delete it. Do you use it and if so is it a necessary part of your implementation?

**Comment by neilotte** [comment]
@mark-jensen We have used it a little, but we could live without it too.

**Comment by mark-jensen** [comment]
After some discussion we decided to delete the process part relations.

**Comment by mark-jensen** [comment]
Addressed in 44c635e

**Comment by mark-jensen** [comment]
After further discussion, we decided to leave the properties intact. They are now subtypes of `has_part` and `part_of`
