### ISSUE TITLE
Group of Agents Axiom

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#80]
For 'Group of Agents' and its subclasses, there are subclass axioms using 'has part' that I think should use 'has member'. 

e.g. 'Group of Agents' has member only cco:Agent /  'Group of Agents' has member some cco:Agent.

**Comment by APCox** [comment]
Agreed. This should be updated for increased accuracy. Though it's worth
noting that since 'has member' is a subrelation of 'has part', the current
axioms are not incorrect.

**Comment by mark-jensen** [comment]
Addressed in 44c635e
