### ISSUE TITLE
Temporal interpretation of relations

### ISSUE THREAD

**Issue by eliasweatherfield** [CommonCoreOntology/CommonCoreOntologies#81]
As you are probably all aware, BFO ISO distinguishes two-place relations from temporalizable three-place relations (e. g. continuant parthood) and distinguished "at all times" and "at some times" versions of the latter.

RO seems to use the "at all times" interpretation for all relations (https://github.com/oborel/obo-relations/wiki/ROAndTime).

Few CCO relations are explicitly defined to hold for all times (e. g. "requires", "permits", "prohibits", "has subordinate role", "occurs in"). 

But the "at all times" interpretation to me does not seem compatible with there being stases ("Stasis"). Is the default temporal interpretation of a CCO relation supposed to be "at some times"? Or does it change from „at all times“ to „at some times“ as soon as a Stasis is defined?

**Comment by eliasweatherfield** [comment]
I should probably flesh this out a little further... my current understanding of a Stasis is that (at least for some relations) it  can be used to represent the temporal region during which a relation is supposed to hold.

A Stasis of Generically Dependent Continuant can be used to represent the temporal region during which an Independent Continuant is carrier_of some Generically Dependent Continuant and a Stasis of Specifically Dependent Continuant can be used to represent the temporal region during which an Indepenent Continuant is bearer_of some Specifically Dependent Continuant.

By the same token, it seems to me that one could define something like a Stasis of Parthood that has_participant some whole and some part and that can be used to represent the temporal region during which some part part_of some whole (or some whohle has_part some part).

Any thoughts? 

Is there an alternative preferred way to represent the temporal region during which some part part_of some whole in CCO?

Thank you.

**Comment by mark-jensen** [comment]
No, using stasis is the correct approach. In the current release of CCO we have a new term for Part Role. This could be used with Stasis of Role to accomplish what you're suggesting without introducing a new class.

**Comment by eliasweatherfield** [comment]
Would it be correct to say that the temporal interpretation of a relation changes from "at all times" to "at some times" if a stasis is present?

**Comment by rorudn** [comment]
my reading of the "at all times" and "at some times" relations is that both are compatible with the use of a stasis. In the former, a has continuant part b at all times implies that if a exists then a has part b, in the latter, a has continuant part b at some time implies that there is a time at which a has part b. So the stasis of parthood_role that Mark described above would be contemporaneous  with the duration of a's existence in the case of "at all times" and would be a sub-interval of that duration in the case of "at some time".

**Comment by eliasweatherfield** [comment]
That would be my reading as well. My reason for opening this issue was that at the time some definitions of relations included the expression „for all x,y,t“ which I at the time (unjustifiedly) assumed to possibly imply an „at all times“ interpretation. I do not think that anymore and also, in the meantime, as far as I can see, the expression I mentioned has been removed from the definitions anyway. Thank you. (I think this can be closed.)
