### ISSUE TITLE
Facility and Infrastructure

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#82]
The classes 'Infrastructure' and 'Facility' are not sufficiently clear to identify whether a given class belongs to one over the other. The wikipedia article that infrastructure links to includes many different senses of the word 'infrastructure', some of which overlap with facility. 

Recommend 'Facility' be restricted to those buildings and campuses containing 0 or more building, where each facility is designed to fulfill a specific function (as it largely is now), while infrastructure is more narrowly defined as physical networks facilitating transportation, communication, or power functions within large organizations or geopolitical entities. This would make dams and aqueducts facilities, but leaves roads, power lines, and fiber optic cable networks under infrastructure. Right now, classes like 'power transmission line' seem like clear cases of infrastructure, but are under facility.

**Comment by rorudn** [comment]
An infrastructure role has been introduced in version 1.3 and Infrastructure has been made a defined class.
