### ISSUE TITLE
ThreeDimensionalPath, ThreeDimensionalPosition

### ISSUE THREAD

**Issue by alanruttenberg** [CommonCoreOntology/CommonCoreOntologies#83]
Hi,
I was staring to look through CCO and figured I'd collect things that caught my eye. I'll put different topics in different issues.

*ThreeDimensionalPath* 
>A Three-Dimensional Spatial Region that encompasses the spatial region through which some Object travels.

*ThreeDimensionalPosition*
>A Three-Dimensional Spatial Region that encompasses the (minimal) spatial region in which some object is located at a particular time.
>For an object in motion, its Three-Dimensional Position is part of its Three-Dimensional Path.

Wouldn't this imply that every ThreeDimensionalPath has at least one part that is a ThreeDimensionalPosition
If so missing an axiom to that effect.

**Comment by mark-jensen** [comment]
I agree that the axiom is implied by the definition and should be added.

**Comment by neilotte** [comment]
This issues has been addressed.
