### ISSUE TITLE
Incorrect subproperty assertions ModalRelationOntology.ttl?

### ISSUE THREAD

**Issue by swartik** [CommonCoreOntology/CommonCoreOntologies#86]
In ModalRelationOntology.ttl, all the object properties are subproperties of cco:ModalObjectProperty. Should they be subproperties of _mro_:ModalObjectProperty?

**Comment by mark-jensen** [comment]
@swartik Thanks for the catch! Fixing asap

**Comment by mark-jensen** [comment]
Addressed with 0a94bd2
