### ISSUE TITLE
Updating to BFO-2020

### ISSUE THREAD

**Issue by neilotte** [CommonCoreOntology/CommonCoreOntologies#88]
Is there an ETA on when CCO will use BFO-2020 and guidance on which version of its relations (temporal or non temporal) will be used?

Context: The class 'process profile' is not in BFO-2020 and I believe the plan is to cede it to CCO. However, some within the IOF are extending from BFO-2020 and CCO 1.3 and so lack a URI at present for 'process profile'. Hence, a more particular question: Will CCO be re-creating 'process profile' and when?

**Comment by rorudn** [comment]
The reasons for not using BFO-2020 in release 1.3 was our understanding that at least some of our user base was reluctant to embrace the temporalized object properties it includes and that the governance of CCO is becoming more inclusive. We thought the decision to move to BFO-2020 was significant enough to warrant its being made by this new governance panel.

The side effect of users of BFO-2020 and CC0 1.3 losing process profile warrants a patch release. The timing will be within the week, if not, then certainly by the end of October.

**Comment by neilotte** [comment]
Makes sense. Thanks Ron!
