### ISSUE TITLE
Need Module Standardization for Common User Profile Use Case

### ISSUE THREAD

**Issue by rockc15** [CommonCoreOntology/CommonCoreOntologies#89]
The Zip file below contains the use case for the Common User Profile Modules, which includes ttl files and sample queries. The files and contents of the CUP were created Mark Jensen and will be used in the SOLID project.

For SOLID project to continue we need the two modules to be included in the standardization process: 

- UserProfileCCOSubset.ttl

- UserProfileExtensionOntology.ttl

[user-profile-2020-03-25.zip](https://github.com/CommonCoreOntology/CommonCoreOntologies/files/5417116/user-profile-2020-03-25.zip)

**Comment by cameronmore** [comment]
As modules that extend from or consist of subsets of the CCO, they are out of scope of changes to the CCO itself.
