### ISSUE TITLE
Artifact Status 

### ISSUE THREAD

**Issue by fameri** [CommonCoreOntology/CommonCoreOntologies#9]
My question pertains to section 4.12 (Effect of Aircraft Maintenance), page 19, in the document titled " Modeling Information with the Common Core Ontologies". The provided example is about A Non-Mission Capable (NMC )F/A-18 aircraft undergoes maintenance (replacement of center barrel) and is thus restored to Fully Mission Capable (FMC) status.

aircraft 1 ---bearer_of---->NMC 1 --- participates _in ----> stasis of NMC1 

is "NMC 1" an instance of bfo: quality ? Why we can't link the aircraft to its status directly ?

**Comment by rorudn** [comment]
The aircraft is linked directly to the stasis as is the instance of the non-mission capable disposition. If your question is why not link **only** the aircraft to the stasis then the answer is that the instance of the nmc disposition adds semantics to the graph. For example I might ask: Which mission functions does a craft in NMC stasis lack? Tracing the stasis back to the aggregate disposition and from there out to the functions it has contra the functions its supposed to have allows me to answer the question.

**Comment by fameri** [comment]
Thanks Ron for clarification.
